-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\Addressable_Delay_Line_block9.vhd
-- Created: 2026-01-30 11:58:51
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Addressable_Delay_Line_block9
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF2/FIRPartlySerial/Addressable_Delay_Line
-- Hierarchy Level: 3
-- Model version: 17.90
-- 
-- Addressable Delay Line
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Addressable_Delay_Line_block9 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
        wrEn                              :   IN    std_logic;
        delayLineEnd                      :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En12
        );
END Addressable_Delay_Line_block9;


ARCHITECTURE rtl OF Addressable_Delay_Line_block9 IS

  -- Signals
  SIGNAL dataIn_signed                    : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayedSignals0                  : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayedSignals1                  : signed(16 DOWNTO 0);  -- sfix17_En12

BEGIN
  dataIn_signed <= signed(dataIn);

  delay0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayedSignals0 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND wrEn = '1' THEN
        delayedSignals0 <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS delay0_process;


  delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayedSignals1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND wrEn = '1' THEN
        delayedSignals1 <= delayedSignals0;
      END IF;
    END IF;
  END PROCESS delay1_process;


  delayLineEnd <= std_logic_vector(delayedSignals1);

END rtl;

