-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\castSection.vhd
-- Created: 2026-01-26 17:17:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: castSection
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/CICDecimation/castSection
-- Hierarchy Level: 2
-- Model version: 17.86
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY castSection IS
  PORT( gcOut_re                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END castSection;


ARCHITECTURE rtl OF castSection IS

BEGIN
  dataOut_re <= gcOut_re;

END rtl;

