-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\CICDecimation.vhd
-- Created: 2026-01-26 17:17:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CICDecimation
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/CICDecimation
-- Hierarchy Level: 1
-- Model version: 17.86
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CICDecimation IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validOut                          :   OUT   std_logic
        );
END CICDecimation;


ARCHITECTURE rtl OF CICDecimation IS

  -- Component Declarations
  COMPONENT iSection
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataInreg                       :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2
          validInreg                      :   IN    std_logic;
          internalReset                   :   IN    std_logic;
          integOut_re                     :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23
          integOut_im                     :   OUT   std_logic_vector(22 DOWNTO 0)  -- sfix23
          );
  END COMPONENT;

  COMPONENT dsSection
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          integOut_re                     :   IN    std_logic_vector(22 DOWNTO 0);  -- sfix23
          integOut_im                     :   IN    std_logic_vector(22 DOWNTO 0);  -- sfix23
          validInreg                      :   IN    std_logic;
          downsampleVal                   :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
          i_rstout                        :   IN    std_logic;
          dsOut_re                        :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23
          dsOut_im                        :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23
          ds_vout                         :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT cSection
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dsOut_re                        :   IN    std_logic_vector(22 DOWNTO 0);  -- sfix23
          dsOut_im                        :   IN    std_logic_vector(22 DOWNTO 0);  -- sfix23
          ds_vout                         :   IN    std_logic;
          internalReset                   :   IN    std_logic;
          combOut_re                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_E5
          combOut_im                      :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_E5
          c_vout                          :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT gcSection
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          combOut_re                      :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_E5
          combOut_im                      :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_E5
          internalReset                   :   IN    std_logic;
          gcOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT castSection
    PORT( gcOut_re                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dataOut_re                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : iSection
    USE ENTITY work.iSection(rtl);

  FOR ALL : dsSection
    USE ENTITY work.dsSection(rtl);

  FOR ALL : cSection
    USE ENTITY work.cSection(rtl);

  FOR ALL : gcSection
    USE ENTITY work.gcSection(rtl);

  FOR ALL : castSection
    USE ENTITY work.castSection(rtl);

  -- Signals
  SIGNAL softReset                        : std_logic;
  SIGNAL dataIn_signed                    : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL dataInreg                        : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL validInreg                       : std_logic;
  SIGNAL integOut_re                      : std_logic_vector(22 DOWNTO 0);  -- ufix23
  SIGNAL integOut_im                      : std_logic_vector(22 DOWNTO 0);  -- ufix23
  SIGNAL downsampleVal                    : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL dsOut_re                         : std_logic_vector(22 DOWNTO 0);  -- ufix23
  SIGNAL dsOut_im                         : std_logic_vector(22 DOWNTO 0);  -- ufix23
  SIGNAL ds_vout                          : std_logic;
  SIGNAL combOut_re                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL combOut_im                       : std_logic_vector(17 DOWNTO 0);  -- ufix18
  SIGNAL c_vout                           : std_logic;
  SIGNAL intdelay_reg                     : std_logic_vector(8 DOWNTO 0);  -- ufix1 [9]
  SIGNAL validOut_1                       : std_logic;
  SIGNAL invalidOut_1                     : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL gcOut_re                         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dataOut_re                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dataOut_re_signed                : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataOut_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_iSection : iSection
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataInreg => std_logic_vector(dataInreg),  -- sfix2
              validInreg => validInreg,
              internalReset => softReset,
              integOut_re => integOut_re,  -- sfix23
              integOut_im => integOut_im  -- sfix23
              );

  u_dsSection : dsSection
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              integOut_re => integOut_re,  -- sfix23
              integOut_im => integOut_im,  -- sfix23
              validInreg => validInreg,
              downsampleVal => std_logic_vector(downsampleVal),  -- ufix12
              i_rstout => softReset,
              dsOut_re => dsOut_re,  -- sfix23
              dsOut_im => dsOut_im,  -- sfix23
              ds_vout => ds_vout
              );

  u_cSection : cSection
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dsOut_re => dsOut_re,  -- sfix23
              dsOut_im => dsOut_im,  -- sfix23
              ds_vout => ds_vout,
              internalReset => softReset,
              combOut_re => combOut_re,  -- sfix18_E5
              combOut_im => combOut_im,  -- sfix18_E5
              c_vout => c_vout
              );

  u_gcSection : gcSection
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              combOut_re => combOut_re,  -- sfix18_E5
              combOut_im => combOut_im,  -- sfix18_E5
              internalReset => softReset,
              gcOut_re => gcOut_re  -- sfix16_En14
              );

  u_castSection : castSection
    PORT MAP( gcOut_re => gcOut_re,  -- sfix16_En14
              dataOut_re => dataOut_re  -- sfix16_En14
              );

  softReset <= '0';

  dataIn_signed <= signed(dataIn);

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataInreg <= to_signed(16#0#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF softReset = '1' THEN
          dataInreg <= to_signed(16#0#, 2);
        ELSE 
          dataInreg <= dataIn_signed;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validInreg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF softReset = '1' THEN
          validInreg <= '0';
        ELSE 
          validInreg <= validIn;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  downsampleVal <= to_unsigned(16#080#, 12);

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF softReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSE 
          intdelay_reg(0) <= c_vout;
          intdelay_reg(8 DOWNTO 1) <= intdelay_reg(7 DOWNTO 0);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;

  validOut_1 <= intdelay_reg(8);

  invalidOut_1 <= to_signed(16#0000#, 16);

  dataOut_re_signed <= signed(dataOut_re);

  
  dataOut_tmp <= invalidOut_1 WHEN validOut_1 = '0' ELSE
      dataOut_re_signed;

  dataOut <= std_logic_vector(dataOut_tmp);

  validOut <= validOut_1;

END rtl;

