vlib work
vcom  DECIMATOR_pkg.vhd
vcom  iSection.vhd
vcom  dsSection.vhd
vcom  cSection.vhd
vcom  gcSection.vhd
vcom  castSection.vhd
vcom  CICDecimation.vhd
vcom  FilterCoef.vhd
vcom  FilterTapSystolicPreAddWvlIn.vhd
vcom  subFilter.vhd
vcom  Filter.vhd
vcom  DCF.vhd
vcom  partlySerialCtrl.vhd
vcom  FirRdyLogic.vhd
vcom  Addressable_Delay_Line.vhd
vcom  Addressable_Delay_Line_block.vhd
vcom  Addressable_Delay_Line_block1.vhd
vcom  Addressable_Delay_Line_block2.vhd
vcom  FilterTapSystolicPreAdd.vhd
vcom  FIRPartlySerial.vhd
vcom  FirRdyLogic_block.vhd
vcom  Addressable_Delay_Line_block3.vhd
vcom  Addressable_Delay_Line_block4.vhd
vcom  FIRPartlySerial_block.vhd
vcom  sumTree_firdecim.vhd
vcom  HBF1.vhd
vcom  partlySerialCtrl_block.vhd
vcom  FirRdyLogic_block1.vhd
vcom  Addressable_Delay_Line_block5.vhd
vcom  Addressable_Delay_Line_block6.vhd
vcom  Addressable_Delay_Line_block7.vhd
vcom  Addressable_Delay_Line_block8.vhd
vcom  FilterTapSystolicPreAdd_block.vhd
vcom  FIRPartlySerial_block1.vhd
vcom  FirRdyLogic_block2.vhd
vcom  Addressable_Delay_Line_block9.vhd
vcom  Addressable_Delay_Line_block10.vhd
vcom  FIRPartlySerial_block2.vhd
vcom  sumTree_firdecim_block.vhd
vcom  HBF2.vhd
vcom  DECIMATOR.vhd
