-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\dsSection.vhd
-- Created: 2026-01-26 17:17:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dsSection
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/CICDecimation/dsSection
-- Hierarchy Level: 2
-- Model version: 17.86
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dsSection IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        integOut_re                       :   IN    std_logic_vector(22 DOWNTO 0);  -- sfix23
        integOut_im                       :   IN    std_logic_vector(22 DOWNTO 0);  -- sfix23
        validInreg                        :   IN    std_logic;
        downsampleVal                     :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        i_rstout                          :   IN    std_logic;
        dsOut_re                          :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23
        dsOut_im                          :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23
        ds_vout                           :   OUT   std_logic
        );
END dsSection;


ARCHITECTURE rtl OF dsSection IS

  -- Signals
  SIGNAL integOut_re_signed               : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL integOut_im_signed               : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL downsampleVal_unsigned           : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL downSampler_count                : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL dsOut_re_tmp                     : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL dsOut_im_tmp                     : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL ds_vout_1                        : std_logic;

BEGIN
  integOut_re_signed <= signed(integOut_re);

  integOut_im_signed <= signed(integOut_im);

  downsampleVal_unsigned <= unsigned(downsampleVal);

  downSampler_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      downSampler_count <= to_unsigned(16#000#, 9);
      dsOut_re_tmp <= to_signed(16#000000#, 23);
      dsOut_im_tmp <= to_signed(16#000000#, 23);
      ds_vout_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF i_rstout /= '0' THEN 
          dsOut_re_tmp <= to_signed(16#000000#, 23);
        ELSIF (validInreg /= '0') AND (downSampler_count = to_unsigned(16#000#, 9)) THEN 
          dsOut_re_tmp <= integOut_re_signed;
        END IF;
        IF i_rstout /= '0' THEN 
          dsOut_im_tmp <= to_signed(16#000000#, 23);
        ELSIF (validInreg /= '0') AND (downSampler_count = to_unsigned(16#000#, 9)) THEN 
          dsOut_im_tmp <= integOut_im_signed;
        END IF;
        IF i_rstout /= '0' THEN 
          ds_vout_1 <= '0';
        ELSIF (validInreg /= '0') AND (downSampler_count = to_unsigned(16#000#, 9)) THEN 
          ds_vout_1 <= '1';
        ELSE 
          ds_vout_1 <= '0';
        END IF;
        IF i_rstout /= '0' THEN 
          downSampler_count <= to_unsigned(16#000#, 9);
        ELSIF validInreg /= '0' THEN 
          IF resize(downSampler_count, 12) < to_unsigned(16#07F#, 12) THEN 
            downSampler_count <= downSampler_count + to_unsigned(16#001#, 9);
          ELSE 
            downSampler_count <= to_unsigned(16#000#, 9);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS downSampler_process;


  dsOut_re <= std_logic_vector(dsOut_re_tmp);

  dsOut_im <= std_logic_vector(dsOut_im_tmp);

  ds_vout <= ds_vout_1;

END rtl;

