-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\FilterCoef.vhd
-- Created: 2026-01-30 10:42:36
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterCoef
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/DCF/Filter/FilterCoef
-- Hierarchy Level: 3
-- Model version: 17.88
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DECIMATOR_pkg.ALL;

ENTITY FilterCoef IS
  PORT( CoefOut                           :   OUT   vector_of_std_logic_vector16(0 TO 12)  -- sfix16_En16 [13]
        );
END FilterCoef;


ARCHITECTURE rtl OF FilterCoef IS

  -- Signals
  SIGNAL CoefData                         : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_1                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_2                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_3                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_4                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_5                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_6                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_7                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_8                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_9                       : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_10                      : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_11                      : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefData_12                      : signed(15 DOWNTO 0);  -- sfix16_En16
  SIGNAL CoefOut_tmp                      : vector_of_signed16(0 TO 12);  -- sfix16_En16 [13]

BEGIN
  -- CoefReg_1
  CoefData <= to_signed(16#025D#, 16);

  -- CoefReg_2
  CoefData_1 <= to_signed(16#02FA#, 16);

  -- CoefReg_3
  CoefData_2 <= to_signed(-16#085A#, 16);

  -- CoefReg_4
  CoefData_3 <= to_signed(-16#12CF#, 16);

  -- CoefReg_5
  CoefData_4 <= to_signed(16#0AB6#, 16);

  -- CoefReg_6
  CoefData_5 <= to_signed(16#4FA8#, 16);

  -- CoefReg_7
  CoefData_6 <= to_signed(16#7674#, 16);

  -- CoefReg_8
  CoefData_7 <= to_signed(16#4FA8#, 16);

  -- CoefReg_9
  CoefData_8 <= to_signed(16#0AB6#, 16);

  -- CoefReg_10
  CoefData_9 <= to_signed(-16#12CF#, 16);

  -- CoefReg_11
  CoefData_10 <= to_signed(-16#085A#, 16);

  -- CoefReg_12
  CoefData_11 <= to_signed(16#02FA#, 16);

  -- CoefReg_13
  CoefData_12 <= to_signed(16#025D#, 16);

  CoefOut_tmp(0) <= CoefData;
  CoefOut_tmp(1) <= CoefData_1;
  CoefOut_tmp(2) <= CoefData_2;
  CoefOut_tmp(3) <= CoefData_3;
  CoefOut_tmp(4) <= CoefData_4;
  CoefOut_tmp(5) <= CoefData_5;
  CoefOut_tmp(6) <= CoefData_6;
  CoefOut_tmp(7) <= CoefData_7;
  CoefOut_tmp(8) <= CoefData_8;
  CoefOut_tmp(9) <= CoefData_9;
  CoefOut_tmp(10) <= CoefData_10;
  CoefOut_tmp(11) <= CoefData_11;
  CoefOut_tmp(12) <= CoefData_12;

  outputgen: FOR k IN 0 TO 12 GENERATE
    CoefOut(k) <= std_logic_vector(CoefOut_tmp(k));
  END GENERATE;

END rtl;

