-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\FilterTapSystolicPreAdd.vhd
-- Created: 2026-01-30 11:58:51
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterTapSystolicPreAdd
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/FIRPartlySerial/FilterTapSystolicPreAdd
-- Hierarchy Level: 3
-- Model version: 17.90
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FilterTapSystolicPreAdd IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        din_re                            :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En13
        preAddIn                          :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En13
        coeff                             :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En16
        sumIn                             :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En29
        sumOut                            :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33_En29
        );
END FilterTapSystolicPreAdd;


ARCHITECTURE rtl OF FilterTapSystolicPreAdd IS

  -- Signals
  SIGNAL din_re_signed                    : signed(16 DOWNTO 0);  -- sfix17_En13
  SIGNAL preAddIn_signed                  : signed(16 DOWNTO 0);  -- sfix17_En13
  SIGNAL coeff_signed                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL sumIn_signed                     : signed(32 DOWNTO 0);  -- sfix33_En29
  SIGNAL fTap_din1_reg1                   : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL fTap_din1_reg2                   : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL fTap_din2_reg1                   : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL fTap_preAdd_reg                  : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL fTap_mult_reg                    : signed(34 DOWNTO 0);  -- sfix35
  SIGNAL fTap_addout_reg                  : signed(32 DOWNTO 0);  -- sfix33
  SIGNAL fTap_coef_reg1                   : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL fTap_coef_reg2                   : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL fTap_preAdd_reg_next             : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL fTap_mult_reg_next               : signed(34 DOWNTO 0);  -- sfix35_En29
  SIGNAL fTap_addout_reg_next             : signed(32 DOWNTO 0);  -- sfix33_En29
  SIGNAL fTap_add_cast                    : signed(32 DOWNTO 0);  -- sfix33_En29
  SIGNAL fTap_add_cast_1                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL fTap_add_cast_2                  : signed(17 DOWNTO 0);  -- sfix18_En13
  SIGNAL sumOut_tmp                       : signed(32 DOWNTO 0);  -- sfix33_En29

BEGIN
  din_re_signed <= signed(din_re);

  preAddIn_signed <= signed(preAddIn);

  coeff_signed <= signed(coeff);

  sumIn_signed <= signed(sumIn);

  -- FilterTapSystolicPreAddS
  fTap_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      fTap_din1_reg1 <= to_signed(16#00000#, 17);
      fTap_din1_reg2 <= to_signed(16#00000#, 17);
      fTap_din2_reg1 <= to_signed(16#00000#, 17);
      fTap_preAdd_reg <= to_signed(16#00000#, 18);
      fTap_coef_reg1 <= to_signed(16#00000#, 17);
      fTap_coef_reg2 <= to_signed(16#00000#, 17);
      fTap_mult_reg <= to_signed(0, 35);
      fTap_addout_reg <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        fTap_preAdd_reg <= fTap_preAdd_reg_next;
        fTap_mult_reg <= fTap_mult_reg_next;
        fTap_addout_reg <= fTap_addout_reg_next;
        fTap_din1_reg2 <= fTap_din1_reg1;
        fTap_din1_reg1 <= din_re_signed;
        fTap_din2_reg1 <= preAddIn_signed;
        fTap_coef_reg2 <= fTap_coef_reg1;
        fTap_coef_reg1 <= coeff_signed;
      END IF;
    END IF;
  END PROCESS fTap_process;

  sumOut_tmp <= fTap_addout_reg;
  fTap_add_cast <= fTap_mult_reg(32 DOWNTO 0);
  fTap_addout_reg_next <= fTap_add_cast + sumIn_signed;
  fTap_mult_reg_next <= fTap_preAdd_reg * fTap_coef_reg2;
  fTap_add_cast_1 <= resize(fTap_din1_reg2, 18);
  fTap_add_cast_2 <= resize(fTap_din2_reg1, 18);
  fTap_preAdd_reg_next <= fTap_add_cast_1 + fTap_add_cast_2;

  sumOut <= std_logic_vector(sumOut_tmp);

END rtl;

