-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\FIRPartlySerial.vhd
-- Created: 2026-01-26 17:17:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FIRPartlySerial
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/FIRPartlySerial
-- Hierarchy Level: 2
-- Model version: 17.86
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FIRPartlySerial IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        filterInput                       :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
        ctrl                              :   IN    std_logic;
        subfilterOutTmp_1                 :   OUT   std_logic_vector(67 DOWNTO 0)  -- sfix68_En63
        );
END FIRPartlySerial;


ARCHITECTURE rtl OF FIRPartlySerial IS

  -- Component Declarations
  COMPONENT FirRdyLogic
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinSwitch                       :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          dinVldSwitch                    :   IN    std_logic;
          coeff                           :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          haltProcess                     :   IN    std_logic;
          dinSM                           :   OUT   std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          dinVldSM                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Addressable_Delay_Line
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          wrEn                            :   IN    std_logic;
          rdAddr                          :   IN    std_logic;  -- ufix1
          delayLineEnd                    :   OUT   std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          dataOut                         :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En30
          );
  END COMPONENT;

  COMPONENT Addressable_Delay_Line_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          wrEn                            :   IN    std_logic;
          rdAddr                          :   IN    std_logic;  -- ufix1
          delayLineEnd                    :   OUT   std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          dataOut                         :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En30
          );
  END COMPONENT;

  COMPONENT Addressable_Delay_Line_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          validIn                         :   IN    std_logic;
          lutaddr                         :   IN    std_logic;  -- ufix1
          delayLineEnd                    :   OUT   std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          dataOut                         :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En30
          );
  END COMPONENT;

  COMPONENT Addressable_Delay_Line_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          validIn                         :   IN    std_logic;
          rdAddr                          :   IN    std_logic;  -- ufix1
          delayLineEnd                    :   OUT   std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          dataOut                         :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En30
          );
  END COMPONENT;

  COMPONENT FilterTapSystolicPreAdd
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din_re                          :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          preAddIn                        :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          coeff                           :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En33
          sumIn                           :   IN    std_logic_vector(66 DOWNTO 0);  -- sfix67_En63
          sumOut                          :   OUT   std_logic_vector(66 DOWNTO 0)  -- sfix67_En63
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FirRdyLogic
    USE ENTITY work.FirRdyLogic(rtl);

  FOR ALL : Addressable_Delay_Line
    USE ENTITY work.Addressable_Delay_Line(rtl);

  FOR ALL : Addressable_Delay_Line_block
    USE ENTITY work.Addressable_Delay_Line_block(rtl);

  FOR ALL : Addressable_Delay_Line_block1
    USE ENTITY work.Addressable_Delay_Line_block1(rtl);

  FOR ALL : Addressable_Delay_Line_block2
    USE ENTITY work.Addressable_Delay_Line_block2(rtl);

  FOR ALL : FilterTapSystolicPreAdd
    USE ENTITY work.FilterTapSystolicPreAdd(rtl);

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL coeff                            : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL haltProcess                      : std_logic;
  SIGNAL dinSM                            : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL dinVldSM                         : std_logic;
  SIGNAL nextDelayLineRdAddrReverse       : std_logic;  -- ufix1
  SIGNAL rdCountReverse_1                 : std_logic;  -- ufix1
  SIGNAL nextDelayLineWrAddr              : std_logic;  -- ufix1
  SIGNAL wrCount_1                        : std_logic;  -- ufix1
  SIGNAL nextDelayLineRdAddr              : std_logic;  -- ufix1
  SIGNAL rdCount_1                        : std_logic;  -- ufix1
  SIGNAL nextSharingCount                 : std_logic;  -- ufix1
  SIGNAL sharingCount_1                   : std_logic;  -- ufix1
  SIGNAL delayLineValidInP                : std_logic;
  SIGNAL lastPhaseStrobe                  : std_logic;
  SIGNAL delayLineShiftEnP                : std_logic;
  SIGNAL delayLineShiftEn1_1              : std_logic;
  SIGNAL delayLineShiftEn2_1              : std_logic;
  SIGNAL delayLineShiftEn3_1              : std_logic;
  SIGNAL delayLineShiftEn4_1              : std_logic;
  SIGNAL validOutLookahead_reg            : std_logic_vector(6 DOWNTO 0);  -- ufix1 [7]
  SIGNAL validOutLookahead_1              : std_logic;
  SIGNAL vldOut_1                         : std_logic;
  SIGNAL notValid                         : std_logic;
  SIGNAL rdAddr0_1                        : std_logic;  -- ufix1
  SIGNAL rdAddr1                          : std_logic;  -- ufix1
  SIGNAL rdAddr2                          : std_logic;  -- ufix1
  SIGNAL rdAddr3                          : std_logic;  -- ufix1
  SIGNAL rdAddr4                          : std_logic;  -- ufix1
  SIGNAL rdAddrEndZero                    : std_logic;
  SIGNAL finalSumValidPipe_reg            : std_logic_vector(5 DOWNTO 0);  -- ufix1 [6]
  SIGNAL accumulate                       : std_logic;
  SIGNAL accDataOut                       : signed(66 DOWNTO 0);  -- sfix67_En63
  SIGNAL delayLineEnd0                    : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineDataOut0                : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineEnd0_signed             : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLineDataIn1_1               : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLineEnd1                    : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineDataOut1                : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineEnd1_signed             : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLineDataIn2_1               : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLineEnd2                    : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineDataOut2                : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineEnd2_signed             : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLineDataIn3_1               : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLineEnd3                    : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineDataOut3                : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineEnd3_signed             : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLineDataIn4_1               : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLineEnd4                    : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineDataOut4                : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL coeffTableOut3                   : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL coeffTableRegP3_1                : signed(33 DOWNTO 0) := to_signed(0, 34);  -- sfix34_En33
  SIGNAL coeffTableReg3_1                 : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL delayLineEnd5                    : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineDataOut5                : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL coeffTableOut2                   : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL coeffTableRegP2_1                : signed(33 DOWNTO 0) := to_signed(0, 34);  -- sfix34_En33
  SIGNAL coeffTableReg2_1                 : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL delayLineEnd6                    : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineDataOut6                : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL coeffTableOut1                   : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL coeffTableRegP1_1                : signed(33 DOWNTO 0) := to_signed(0, 34);  -- sfix34_En33
  SIGNAL coeffTableReg1_1                 : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL delayLineEnd7deadOut             : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL delayLineDataOut7                : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL coeffTableOut0                   : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL coeffTableRegP0_1                : signed(33 DOWNTO 0) := to_signed(0, 34);  -- sfix34_En33
  SIGNAL coeffTableReg0_1                 : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL sumIn                            : signed(66 DOWNTO 0);  -- sfix67_En63
  SIGNAL sumOut                           : std_logic_vector(66 DOWNTO 0);  -- ufix67
  SIGNAL sumOut_0                         : std_logic_vector(66 DOWNTO 0);  -- ufix67
  SIGNAL sumOut_1                         : std_logic_vector(66 DOWNTO 0);  -- ufix67
  SIGNAL sumOut_2                         : std_logic_vector(66 DOWNTO 0);  -- ufix67
  SIGNAL sumOut_2_signed                  : signed(66 DOWNTO 0);  -- sfix67_En63
  SIGNAL sumOutReg_1                      : signed(66 DOWNTO 0);  -- sfix67_En63
  SIGNAL accDataOut_1                     : signed(66 DOWNTO 0);  -- sfix67_En63
  SIGNAL accSwitchOut                     : signed(66 DOWNTO 0);  -- sfix67_En63
  SIGNAL accAdderOut                      : signed(66 DOWNTO 0);  -- sfix67_En63
  SIGNAL converterOut                     : signed(67 DOWNTO 0);  -- sfix68_En63
  SIGNAL dout_re_1                        : signed(67 DOWNTO 0);  -- sfix68_En63
  SIGNAL dataZero                         : signed(67 DOWNTO 0);  -- sfix68_En63
  SIGNAL subfilterOutTmp_1_tmp            : signed(67 DOWNTO 0);  -- sfix68_En63

BEGIN
  u_firRdyLogic : FirRdyLogic
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinSwitch => filterInput,  -- sfix34_En30
              dinVldSwitch => ctrl,
              coeff => std_logic_vector(coeff),  -- sfix34_En30
              haltProcess => haltProcess,
              dinSM => dinSM,  -- sfix34_En30
              dinVldSM => dinVldSM
              );

  u_delayLine0 : Addressable_Delay_Line
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => dinSM,  -- sfix34_En30
              wrEn => delayLineValidInP,
              rdAddr => rdAddr0_1,  -- ufix1
              delayLineEnd => delayLineEnd0,  -- sfix34_En30
              dataOut => delayLineDataOut0  -- sfix34_En30
              );

  u_delayLine1 : Addressable_Delay_Line
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn1_1),  -- sfix34_En30
              wrEn => delayLineShiftEn1_1,
              rdAddr => rdAddr1,  -- ufix1
              delayLineEnd => delayLineEnd1,  -- sfix34_En30
              dataOut => delayLineDataOut1  -- sfix34_En30
              );

  u_delayLine2 : Addressable_Delay_Line
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn2_1),  -- sfix34_En30
              wrEn => delayLineShiftEn2_1,
              rdAddr => rdAddr2,  -- ufix1
              delayLineEnd => delayLineEnd2,  -- sfix34_En30
              dataOut => delayLineDataOut2  -- sfix34_En30
              );

  u_delayLine3 : Addressable_Delay_Line_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn3_1),  -- sfix34_En30
              wrEn => delayLineShiftEn3_1,
              rdAddr => rdAddr3,  -- ufix1
              delayLineEnd => delayLineEnd3,  -- sfix34_En30
              dataOut => delayLineDataOut3  -- sfix34_En30
              );

  u_delayLine4 : Addressable_Delay_Line_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn4_1),  -- sfix34_En30
              validIn => delayLineShiftEn4_1,
              lutaddr => rdAddr4,  -- ufix1
              delayLineEnd => delayLineEnd4,  -- sfix34_En30
              dataOut => delayLineDataOut4  -- sfix34_En30
              );

  u_delayLine5 : Addressable_Delay_Line_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => delayLineEnd4,  -- sfix34_En30
              validIn => delayLineShiftEn3_1,
              rdAddr => rdAddr3,  -- ufix1
              delayLineEnd => delayLineEnd5,  -- sfix34_En30
              dataOut => delayLineDataOut5  -- sfix34_En30
              );

  u_delayLine6 : Addressable_Delay_Line_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => delayLineEnd5,  -- sfix34_En30
              validIn => delayLineShiftEn2_1,
              rdAddr => rdAddr2,  -- ufix1
              delayLineEnd => delayLineEnd6,  -- sfix34_En30
              dataOut => delayLineDataOut6  -- sfix34_En30
              );

  u_delayLine7 : Addressable_Delay_Line_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => delayLineEnd6,  -- sfix34_En30
              validIn => delayLineShiftEn1_1,
              rdAddr => rdAddr1,  -- ufix1
              delayLineEnd => delayLineEnd7deadOut,  -- sfix34_En30
              dataOut => delayLineDataOut7  -- sfix34_En30
              );

  u_filterTap0 : FilterTapSystolicPreAdd
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut0,  -- sfix34_En30
              preAddIn => delayLineDataOut7,  -- sfix34_En30
              coeff => std_logic_vector(coeffTableReg0_1),  -- sfix34_En33
              sumIn => std_logic_vector(sumIn),  -- sfix67_En63
              sumOut => sumOut  -- sfix67_En63
              );

  u_filterTap1 : FilterTapSystolicPreAdd
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut1,  -- sfix34_En30
              preAddIn => delayLineDataOut6,  -- sfix34_En30
              coeff => std_logic_vector(coeffTableReg1_1),  -- sfix34_En33
              sumIn => sumOut,  -- sfix67_En63
              sumOut => sumOut_0  -- sfix67_En63
              );

  u_filterTap2 : FilterTapSystolicPreAdd
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut2,  -- sfix34_En30
              preAddIn => delayLineDataOut5,  -- sfix34_En30
              coeff => std_logic_vector(coeffTableReg2_1),  -- sfix34_En33
              sumIn => sumOut_0,  -- sfix67_En63
              sumOut => sumOut_1  -- sfix67_En63
              );

  u_filterTap3 : FilterTapSystolicPreAdd
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut3,  -- sfix34_En30
              preAddIn => delayLineDataOut4,  -- sfix34_En30
              coeff => std_logic_vector(coeffTableReg3_1),  -- sfix34_En33
              sumIn => sumOut_1,  -- sfix67_En63
              sumOut => sumOut_2  -- sfix67_En63
              );

  coeff <= to_signed(0, 34);

  haltProcess <= '0';

  rdCountReverse_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdCountReverse_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdCountReverse_1 <= nextDelayLineRdAddrReverse;
      END IF;
    END IF;
  END PROCESS rdCountReverse_process;


  wrCount_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      wrCount_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        wrCount_1 <= nextDelayLineWrAddr;
      END IF;
    END IF;
  END PROCESS wrCount_process;


  rdCount_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdCount_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdCount_1 <= nextDelayLineRdAddr;
      END IF;
    END IF;
  END PROCESS rdCount_process;


  sharingCount_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sharingCount_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sharingCount_1 <= nextSharingCount;
      END IF;
    END IF;
  END PROCESS sharingCount_process;


  -- Input control counter combinatorial logic
  InputControl_output : PROCESS (dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1)
    VARIABLE out4 : std_logic;
    VARIABLE add_cast : unsigned(1 DOWNTO 0);
    VARIABLE add_temp : unsigned(1 DOWNTO 0);
    VARIABLE add_cast_0 : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_0 : unsigned(1 DOWNTO 0);
    VARIABLE sub_cast : unsigned(1 DOWNTO 0);
    VARIABLE sub_temp : unsigned(1 DOWNTO 0);
    VARIABLE add_cast_1 : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_1 : unsigned(1 DOWNTO 0);
    VARIABLE add_cast_2 : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_2 : unsigned(1 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(16#0#, 2);
    add_temp_0 := to_unsigned(16#0#, 2);
    sub_temp := to_unsigned(16#0#, 2);
    add_temp_1 := to_unsigned(16#0#, 2);
    add_temp_2 := to_unsigned(16#0#, 2);
    add_cast_2 := to_unsigned(16#0#, 2);
    add_cast_1 := to_unsigned(16#0#, 2);
    sub_cast := to_unsigned(16#0#, 2);
    add_cast_0 := to_unsigned(16#0#, 2);
    add_cast := to_unsigned(16#0#, 2);
    delayLineValidInP <= hdlcoder_to_stdlogic((sharingCount_1 = '0') AND (dinVldSM = '1'));
    lastPhaseStrobe <= sharingCount_1;
    IF (dinVldSM = '1') OR (sharingCount_1 > '0') THEN 
      IF sharingCount_1 = '1' THEN 
        nextSharingCount <= '0';
      ELSE 
        add_cast := '0' & sharingCount_1;
        add_temp := add_cast + to_unsigned(16#1#, 2);
        nextSharingCount <= add_temp(0);
      END IF;
    ELSE 
      nextSharingCount <= sharingCount_1;
    END IF;
    IF dinVldSM = '1' THEN 
      IF wrCount_1 = '1' THEN 
        out4 := '0';
      ELSE 
        add_cast_0 := '0' & wrCount_1;
        add_temp_0 := add_cast_0 + to_unsigned(16#1#, 2);
        out4 := add_temp_0(0);
      END IF;
    ELSE 
      out4 := wrCount_1;
    END IF;
    IF (rdCount_1 /= out4) OR (dinVldSM = '1') THEN 
      IF rdCount_1 = '0' THEN 
        nextDelayLineRdAddr <= '1';
      ELSE 
        sub_cast := '0' & rdCount_1;
        sub_temp := sub_cast - to_unsigned(16#1#, 2);
        nextDelayLineRdAddr <= sub_temp(0);
      END IF;
    ELSE 
      nextDelayLineRdAddr <= rdCount_1;
    END IF;
    IF (sharingCount_1 > '0') OR (dinVldSM = '1') THEN 
      IF sharingCount_1 = '1' THEN 
        IF wrCount_1 = '1' THEN 
          nextDelayLineRdAddrReverse <= '0';
        ELSE 
          add_cast_2 := '0' & wrCount_1;
          add_temp_2 := add_cast_2 + to_unsigned(16#1#, 2);
          nextDelayLineRdAddrReverse <= add_temp_2(0);
        END IF;
      ELSIF rdCountReverse_1 = '1' THEN 
        nextDelayLineRdAddrReverse <= '0';
      ELSE 
        add_cast_1 := '0' & rdCountReverse_1;
        add_temp_1 := add_cast_1 + to_unsigned(16#1#, 2);
        nextDelayLineRdAddrReverse <= add_temp_1(0);
      END IF;
    ELSE 
      nextDelayLineRdAddrReverse <= rdCountReverse_1;
    END IF;
    nextDelayLineWrAddr <= out4;
  END PROCESS InputControl_output;


  delayLineShiftEn0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEnP <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEnP <= lastPhaseStrobe;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn0_process;


  delayLineShiftEn1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn1_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn1_1 <= delayLineShiftEnP;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn1_process;


  delayLineShiftEn2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn2_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn2_1 <= delayLineShiftEn1_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn2_process;


  delayLineShiftEn3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn3_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn3_1 <= delayLineShiftEn2_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn3_process;


  delayLineShiftEn4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn4_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn4_1 <= delayLineShiftEn3_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn4_process;


  validOutLookahead_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOutLookahead_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        validOutLookahead_reg(0) <= delayLineShiftEn4_1;
        validOutLookahead_reg(6 DOWNTO 1) <= validOutLookahead_reg(5 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS validOutLookahead_process;

  validOutLookahead_1 <= validOutLookahead_reg(6);

  vldOut_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      vldOut_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        vldOut_1 <= validOutLookahead_1;
      END IF;
    END IF;
  END PROCESS vldOut_process;


  notValid <=  NOT vldOut_1;

  rdAddr0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr0_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr0_1 <= sharingCount_1;
      END IF;
    END IF;
  END PROCESS rdAddr0_process;


  rdAddr0_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr1 <= rdAddr0_1;
      END IF;
    END IF;
  END PROCESS rdAddr0_2_process;


  rdAddr1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr2 <= rdAddr1;
      END IF;
    END IF;
  END PROCESS rdAddr1_1_process;


  rdAddr2_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr3 <= rdAddr2;
      END IF;
    END IF;
  END PROCESS rdAddr2_1_process;


  rdAddr3_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr4 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr4 <= rdAddr3;
      END IF;
    END IF;
  END PROCESS rdAddr3_1_process;


  rdAddrEndZero <=  NOT rdAddr4;

  finalSumValidPipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      finalSumValidPipe_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        finalSumValidPipe_reg(0) <= rdAddrEndZero;
        finalSumValidPipe_reg(5 DOWNTO 1) <= finalSumValidPipe_reg(4 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS finalSumValidPipe_process;

  accumulate <= finalSumValidPipe_reg(5);

  accDataOut <= to_signed(0, 67);

  delayLineEnd0_signed <= signed(delayLineEnd0);

  delayLineDataIn1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn1_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn1_1 <= delayLineEnd0_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn1_process;


  delayLineEnd1_signed <= signed(delayLineEnd1);

  delayLineDataIn2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn2_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn2_1 <= delayLineEnd1_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn2_process;


  delayLineEnd2_signed <= signed(delayLineEnd2);

  delayLineDataIn3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn3_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn3_1 <= delayLineEnd2_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn3_process;


  delayLineEnd3_signed <= signed(delayLineEnd3);

  delayLineDataIn4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn4_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn4_1 <= delayLineEnd3_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn4_process;


  -- Coefficient table for multiplier3
  coeffTable3_output : PROCESS (rdAddr3)
  BEGIN
    CASE rdAddr3 IS
      WHEN '0' =>
        coeffTableOut3 <= signed'("0010011111000010100101000000010001");
      WHEN '1' =>
        coeffTableOut3 <= to_signed(0, 34);
      WHEN OTHERS => 
        coeffTableOut3 <= to_signed(0, 34);
    END CASE;
  END PROCESS coeffTable3_output;


  coeffTableRegP3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP3_1 <= coeffTableOut3;
      END IF;
    END IF;
  END PROCESS coeffTableRegP3_process;


  coeffTableReg3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg3_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg3_1 <= coeffTableRegP3_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg3_process;


  -- Coefficient table for multiplier2
  coeffTable2_output : PROCESS (rdAddr2)
  BEGIN
    CASE rdAddr2 IS
      WHEN '0' =>
        coeffTableOut2 <= to_signed(292093648, 34);
      WHEN '1' =>
        coeffTableOut2 <= to_signed(-730112595, 34);
      WHEN OTHERS => 
        coeffTableOut2 <= to_signed(0, 34);
    END CASE;
  END PROCESS coeffTable2_output;


  coeffTableRegP2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP2_1 <= coeffTableOut2;
      END IF;
    END IF;
  END PROCESS coeffTableRegP2_process;


  coeffTableReg2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg2_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg2_1 <= coeffTableRegP2_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg2_process;


  -- Coefficient table for multiplier1
  coeffTable1_output : PROCESS (rdAddr1)
  BEGIN
    CASE rdAddr1 IS
      WHEN '0' =>
        coeffTableOut1 <= to_signed(34263040, 34);
      WHEN '1' =>
        coeffTableOut1 <= to_signed(-110274989, 34);
      WHEN OTHERS => 
        coeffTableOut1 <= to_signed(0, 34);
    END CASE;
  END PROCESS coeffTable1_output;


  coeffTableRegP1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP1_1 <= coeffTableOut1;
      END IF;
    END IF;
  END PROCESS coeffTableRegP1_process;


  coeffTableReg1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg1_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg1_1 <= coeffTableRegP1_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg1_process;


  -- Coefficient table for multiplier0
  coeffTable0_output : PROCESS (rdAddr0_1)
  BEGIN
    CASE rdAddr0_1 IS
      WHEN '0' =>
        coeffTableOut0 <= to_signed(937175, 34);
      WHEN '1' =>
        coeffTableOut0 <= to_signed(-7671858, 34);
      WHEN OTHERS => 
        coeffTableOut0 <= to_signed(0, 34);
    END CASE;
  END PROCESS coeffTable0_output;


  coeffTableRegP0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP0_1 <= coeffTableOut0;
      END IF;
    END IF;
  END PROCESS coeffTableRegP0_process;


  coeffTableReg0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg0_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg0_1 <= coeffTableRegP0_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg0_process;


  sumIn <= to_signed(0, 67);

  sumOut_2_signed <= signed(sumOut_2);

  sumOutReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumOutReg_1 <= to_signed(0, 67);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sumOutReg_1 <= sumOut_2_signed;
      END IF;
    END IF;
  END PROCESS sumOutReg_process;


  
  accSwitchOut <= accDataOut_1 WHEN accumulate = '0' ELSE
      accDataOut;

  accAdderOut <= accSwitchOut + sumOutReg_1;

  accDataOut_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accDataOut_1 <= to_signed(0, 67);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        accDataOut_1 <= accAdderOut;
      END IF;
    END IF;
  END PROCESS accDataOut_2_process;


  converterOut <= resize(accDataOut_1, 68);

  dout_re_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dout_re_1 <= to_signed(0, 68);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND validOutLookahead_1 = '1' THEN
        dout_re_1 <= converterOut;
      END IF;
    END IF;
  END PROCESS dout_re_process;


  dataZero <= to_signed(0, 68);

  
  subfilterOutTmp_1_tmp <= dout_re_1 WHEN notValid = '0' ELSE
      dataZero;

  subfilterOutTmp_1 <= std_logic_vector(subfilterOutTmp_1_tmp);

END rtl;

