-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\FIRPartlySerial_block1.vhd
-- Created: 2026-01-30 10:42:36
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FIRPartlySerial_block1
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF2/FIRPartlySerial
-- Hierarchy Level: 2
-- Model version: 17.88
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FIRPartlySerial_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        filterInput                       :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
        ctrl                              :   IN    std_logic;
        subfilterOutTmp_1                 :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En28
        );
END FIRPartlySerial_block1;


ARCHITECTURE rtl OF FIRPartlySerial_block1 IS

  -- Component Declarations
  COMPONENT FirRdyLogic_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinSwitch                       :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          dinVldSwitch                    :   IN    std_logic;
          coeff                           :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          haltProcess                     :   IN    std_logic;
          dinSM                           :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          dinVldSM                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Addressable_Delay_Line_block5
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          wrEn                            :   IN    std_logic;
          rdAddr                          :   IN    std_logic;  -- ufix1
          delayLineEnd                    :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          dataOut                         :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En12
          );
  END COMPONENT;

  COMPONENT Addressable_Delay_Line_block6
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          wrEn                            :   IN    std_logic;
          rdAddr                          :   IN    std_logic;  -- ufix1
          delayLineEnd                    :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          dataOut                         :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En12
          );
  END COMPONENT;

  COMPONENT Addressable_Delay_Line_block7
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          validIn                         :   IN    std_logic;
          lutaddr                         :   IN    std_logic;  -- ufix1
          delayLineEnd                    :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          dataOut                         :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En12
          );
  END COMPONENT;

  COMPONENT Addressable_Delay_Line_block8
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          validIn                         :   IN    std_logic;
          rdAddr                          :   IN    std_logic;  -- ufix1
          delayLineEnd                    :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          dataOut                         :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En12
          );
  END COMPONENT;

  COMPONENT FilterTapSystolicPreAdd_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din_re                          :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          preAddIn                        :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En12
          coeff                           :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En16
          sumIn                           :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En28
          sumOut                          :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33_En28
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FirRdyLogic_block1
    USE ENTITY work.FirRdyLogic_block1(rtl);

  FOR ALL : Addressable_Delay_Line_block5
    USE ENTITY work.Addressable_Delay_Line_block5(rtl);

  FOR ALL : Addressable_Delay_Line_block6
    USE ENTITY work.Addressable_Delay_Line_block6(rtl);

  FOR ALL : Addressable_Delay_Line_block7
    USE ENTITY work.Addressable_Delay_Line_block7(rtl);

  FOR ALL : Addressable_Delay_Line_block8
    USE ENTITY work.Addressable_Delay_Line_block8(rtl);

  FOR ALL : FilterTapSystolicPreAdd_block
    USE ENTITY work.FilterTapSystolicPreAdd_block(rtl);

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL coeff                            : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL haltProcess                      : std_logic;
  SIGNAL dinSM                            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL dinVldSM                         : std_logic;
  SIGNAL nextDelayLineRdAddrReverse       : std_logic;  -- ufix1
  SIGNAL rdCountReverse_1                 : std_logic;  -- ufix1
  SIGNAL nextDelayLineWrAddr              : std_logic;  -- ufix1
  SIGNAL wrCount_1                        : std_logic;  -- ufix1
  SIGNAL nextDelayLineRdAddr              : std_logic;  -- ufix1
  SIGNAL rdCount_1                        : std_logic;  -- ufix1
  SIGNAL nextSharingCount                 : std_logic;  -- ufix1
  SIGNAL sharingCount_1                   : std_logic;  -- ufix1
  SIGNAL delayLineValidInP                : std_logic;
  SIGNAL lastPhaseStrobe                  : std_logic;
  SIGNAL delayLineShiftEnP                : std_logic;
  SIGNAL delayLineShiftEn1_1              : std_logic;
  SIGNAL delayLineShiftEn2_1              : std_logic;
  SIGNAL delayLineShiftEn3_1              : std_logic;
  SIGNAL delayLineShiftEn4_1              : std_logic;
  SIGNAL delayLineShiftEn5_1              : std_logic;
  SIGNAL delayLineShiftEn6_1              : std_logic;
  SIGNAL delayLineShiftEn7_1              : std_logic;
  SIGNAL validOutLookahead_reg            : std_logic_vector(6 DOWNTO 0);  -- ufix1 [7]
  SIGNAL validOutLookahead_1              : std_logic;
  SIGNAL vldOut_1                         : std_logic;
  SIGNAL notValid                         : std_logic;
  SIGNAL rdAddr0_1                        : std_logic;  -- ufix1
  SIGNAL rdAddr1                          : std_logic;  -- ufix1
  SIGNAL rdAddr2                          : std_logic;  -- ufix1
  SIGNAL rdAddr3                          : std_logic;  -- ufix1
  SIGNAL rdAddr4                          : std_logic;  -- ufix1
  SIGNAL rdAddr5                          : std_logic;  -- ufix1
  SIGNAL rdAddr6                          : std_logic;  -- ufix1
  SIGNAL rdAddr7                          : std_logic;  -- ufix1
  SIGNAL rdAddrEndZero                    : std_logic;
  SIGNAL finalSumValidPipe_reg            : std_logic_vector(5 DOWNTO 0);  -- ufix1 [6]
  SIGNAL accumulate                       : std_logic;
  SIGNAL accDataOut                       : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL delayLineEnd0                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut0deadOut         : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineEnd0_signed             : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineDataIn1_1               : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineEnd1                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut1                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineEnd1_signed             : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineDataIn2_1               : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineEnd2                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut2                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineEnd2_signed             : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineDataIn3_1               : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineEnd3                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut3                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineEnd3_signed             : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineDataIn4_1               : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineEnd4                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut4                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineEnd4_signed             : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineDataIn5_1               : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineEnd5                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut5                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineEnd5_signed             : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineDataIn6_1               : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineEnd6                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut6                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineEnd6_signed             : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineDataIn7_1               : signed(16 DOWNTO 0);  -- sfix17_En12
  SIGNAL delayLineEnd7                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut7                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL coeffTableOut6                   : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL coeffTableRegP6_1                : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17_En16
  SIGNAL coeffTableReg6_1                 : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL delayLineEnd8                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut8                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL coeffTableOut5                   : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL coeffTableRegP5_1                : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17_En16
  SIGNAL coeffTableReg5_1                 : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL delayLineEnd9                    : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut9                : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL coeffTableOut4                   : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL coeffTableRegP4_1                : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17_En16
  SIGNAL coeffTableReg4_1                 : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL delayLineEnd10                   : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut10               : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL coeffTableOut3                   : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL coeffTableRegP3_1                : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17_En16
  SIGNAL coeffTableReg3_1                 : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL delayLineEnd11                   : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut11               : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL coeffTableOut2                   : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL coeffTableRegP2_1                : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17_En16
  SIGNAL coeffTableReg2_1                 : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL delayLineEnd12deadOut            : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL delayLineDataOut12               : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL coeffTableOut1                   : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL coeffTableRegP1_1                : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17_En16
  SIGNAL coeffTableReg1_1                 : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL sumIn                            : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL sumOut                           : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL sumOut_0                         : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL sumOut_1                         : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL sumOut_2                         : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL sumOut_3                         : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL sumOut_4                         : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL sumOut_5                         : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL sumOut_5_signed                  : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL sumOutReg_1                      : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL accDataOut_1                     : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL accSwitchOut                     : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL accAdderOut                      : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL converterOut                     : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL dout_re_1                        : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL dataZero                         : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL subfilterOutTmp_1_tmp            : signed(33 DOWNTO 0);  -- sfix34_En28

BEGIN
  u_firRdyLogic : FirRdyLogic_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinSwitch => filterInput,  -- sfix17_En12
              dinVldSwitch => ctrl,
              coeff => std_logic_vector(coeff),  -- sfix17_En12
              haltProcess => haltProcess,
              dinSM => dinSM,  -- sfix17_En12
              dinVldSM => dinVldSM
              );

  u_delayLine0 : Addressable_Delay_Line_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => dinSM,  -- sfix17_En12
              wrEn => delayLineValidInP,
              rdAddr => rdAddr0_1,  -- ufix1
              delayLineEnd => delayLineEnd0,  -- sfix17_En12
              dataOut => delayLineDataOut0deadOut  -- sfix17_En12
              );

  u_delayLine1 : Addressable_Delay_Line_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn1_1),  -- sfix17_En12
              wrEn => delayLineShiftEn1_1,
              rdAddr => rdAddr1,  -- ufix1
              delayLineEnd => delayLineEnd1,  -- sfix17_En12
              dataOut => delayLineDataOut1  -- sfix17_En12
              );

  u_delayLine2 : Addressable_Delay_Line_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn2_1),  -- sfix17_En12
              wrEn => delayLineShiftEn2_1,
              rdAddr => rdAddr2,  -- ufix1
              delayLineEnd => delayLineEnd2,  -- sfix17_En12
              dataOut => delayLineDataOut2  -- sfix17_En12
              );

  u_delayLine3 : Addressable_Delay_Line_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn3_1),  -- sfix17_En12
              wrEn => delayLineShiftEn3_1,
              rdAddr => rdAddr3,  -- ufix1
              delayLineEnd => delayLineEnd3,  -- sfix17_En12
              dataOut => delayLineDataOut3  -- sfix17_En12
              );

  u_delayLine4 : Addressable_Delay_Line_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn4_1),  -- sfix17_En12
              wrEn => delayLineShiftEn4_1,
              rdAddr => rdAddr4,  -- ufix1
              delayLineEnd => delayLineEnd4,  -- sfix17_En12
              dataOut => delayLineDataOut4  -- sfix17_En12
              );

  u_delayLine5 : Addressable_Delay_Line_block5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn5_1),  -- sfix17_En12
              wrEn => delayLineShiftEn5_1,
              rdAddr => rdAddr5,  -- ufix1
              delayLineEnd => delayLineEnd5,  -- sfix17_En12
              dataOut => delayLineDataOut5  -- sfix17_En12
              );

  u_delayLine6 : Addressable_Delay_Line_block6
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn6_1),  -- sfix17_En12
              wrEn => delayLineShiftEn6_1,
              rdAddr => rdAddr6,  -- ufix1
              delayLineEnd => delayLineEnd6,  -- sfix17_En12
              dataOut => delayLineDataOut6  -- sfix17_En12
              );

  u_delayLine7 : Addressable_Delay_Line_block7
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(delayLineDataIn7_1),  -- sfix17_En12
              validIn => delayLineShiftEn7_1,
              lutaddr => rdAddr7,  -- ufix1
              delayLineEnd => delayLineEnd7,  -- sfix17_En12
              dataOut => delayLineDataOut7  -- sfix17_En12
              );

  u_delayLine8 : Addressable_Delay_Line_block8
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => delayLineEnd7,  -- sfix17_En12
              validIn => delayLineShiftEn6_1,
              rdAddr => rdAddr6,  -- ufix1
              delayLineEnd => delayLineEnd8,  -- sfix17_En12
              dataOut => delayLineDataOut8  -- sfix17_En12
              );

  u_delayLine9 : Addressable_Delay_Line_block8
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => delayLineEnd8,  -- sfix17_En12
              validIn => delayLineShiftEn5_1,
              rdAddr => rdAddr5,  -- ufix1
              delayLineEnd => delayLineEnd9,  -- sfix17_En12
              dataOut => delayLineDataOut9  -- sfix17_En12
              );

  u_delayLine10 : Addressable_Delay_Line_block8
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => delayLineEnd9,  -- sfix17_En12
              validIn => delayLineShiftEn4_1,
              rdAddr => rdAddr4,  -- ufix1
              delayLineEnd => delayLineEnd10,  -- sfix17_En12
              dataOut => delayLineDataOut10  -- sfix17_En12
              );

  u_delayLine11 : Addressable_Delay_Line_block8
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => delayLineEnd10,  -- sfix17_En12
              validIn => delayLineShiftEn3_1,
              rdAddr => rdAddr3,  -- ufix1
              delayLineEnd => delayLineEnd11,  -- sfix17_En12
              dataOut => delayLineDataOut11  -- sfix17_En12
              );

  u_delayLine12 : Addressable_Delay_Line_block8
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => delayLineEnd11,  -- sfix17_En12
              validIn => delayLineShiftEn2_1,
              rdAddr => rdAddr2,  -- ufix1
              delayLineEnd => delayLineEnd12deadOut,  -- sfix17_En12
              dataOut => delayLineDataOut12  -- sfix17_En12
              );

  u_filterTap1 : FilterTapSystolicPreAdd_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut1,  -- sfix17_En12
              preAddIn => delayLineDataOut12,  -- sfix17_En12
              coeff => std_logic_vector(coeffTableReg1_1),  -- sfix17_En16
              sumIn => std_logic_vector(sumOut),  -- sfix33_En28
              sumOut => sumOut_0  -- sfix33_En28
              );

  u_filterTap2 : FilterTapSystolicPreAdd_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut2,  -- sfix17_En12
              preAddIn => delayLineDataOut11,  -- sfix17_En12
              coeff => std_logic_vector(coeffTableReg2_1),  -- sfix17_En16
              sumIn => sumOut_0,  -- sfix33_En28
              sumOut => sumOut_1  -- sfix33_En28
              );

  u_filterTap3 : FilterTapSystolicPreAdd_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut3,  -- sfix17_En12
              preAddIn => delayLineDataOut10,  -- sfix17_En12
              coeff => std_logic_vector(coeffTableReg3_1),  -- sfix17_En16
              sumIn => sumOut_1,  -- sfix33_En28
              sumOut => sumOut_2  -- sfix33_En28
              );

  u_filterTap4 : FilterTapSystolicPreAdd_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut4,  -- sfix17_En12
              preAddIn => delayLineDataOut9,  -- sfix17_En12
              coeff => std_logic_vector(coeffTableReg4_1),  -- sfix17_En16
              sumIn => sumOut_2,  -- sfix33_En28
              sumOut => sumOut_3  -- sfix33_En28
              );

  u_filterTap5 : FilterTapSystolicPreAdd_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut5,  -- sfix17_En12
              preAddIn => delayLineDataOut8,  -- sfix17_En12
              coeff => std_logic_vector(coeffTableReg5_1),  -- sfix17_En16
              sumIn => sumOut_3,  -- sfix33_En28
              sumOut => sumOut_4  -- sfix33_En28
              );

  u_filterTap6 : FilterTapSystolicPreAdd_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din_re => delayLineDataOut6,  -- sfix17_En12
              preAddIn => delayLineDataOut7,  -- sfix17_En12
              coeff => std_logic_vector(coeffTableReg6_1),  -- sfix17_En16
              sumIn => sumOut_4,  -- sfix33_En28
              sumOut => sumOut_5  -- sfix33_En28
              );

  coeff <= to_signed(16#00000#, 17);

  haltProcess <= '0';

  rdCountReverse_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdCountReverse_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdCountReverse_1 <= nextDelayLineRdAddrReverse;
      END IF;
    END IF;
  END PROCESS rdCountReverse_process;


  wrCount_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      wrCount_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        wrCount_1 <= nextDelayLineWrAddr;
      END IF;
    END IF;
  END PROCESS wrCount_process;


  rdCount_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdCount_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdCount_1 <= nextDelayLineRdAddr;
      END IF;
    END IF;
  END PROCESS rdCount_process;


  sharingCount_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sharingCount_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sharingCount_1 <= nextSharingCount;
      END IF;
    END IF;
  END PROCESS sharingCount_process;


  -- Input control counter combinatorial logic
  InputControl_output : PROCESS (dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1)
    VARIABLE out4 : std_logic;
    VARIABLE add_cast : unsigned(1 DOWNTO 0);
    VARIABLE add_temp : unsigned(1 DOWNTO 0);
    VARIABLE add_cast_0 : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_0 : unsigned(1 DOWNTO 0);
    VARIABLE sub_cast : unsigned(1 DOWNTO 0);
    VARIABLE sub_temp : unsigned(1 DOWNTO 0);
    VARIABLE add_cast_1 : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_1 : unsigned(1 DOWNTO 0);
    VARIABLE add_cast_2 : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_2 : unsigned(1 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(16#0#, 2);
    add_temp_0 := to_unsigned(16#0#, 2);
    sub_temp := to_unsigned(16#0#, 2);
    add_temp_1 := to_unsigned(16#0#, 2);
    add_temp_2 := to_unsigned(16#0#, 2);
    add_cast_2 := to_unsigned(16#0#, 2);
    add_cast_1 := to_unsigned(16#0#, 2);
    sub_cast := to_unsigned(16#0#, 2);
    add_cast_0 := to_unsigned(16#0#, 2);
    add_cast := to_unsigned(16#0#, 2);
    delayLineValidInP <= hdlcoder_to_stdlogic((sharingCount_1 = '0') AND (dinVldSM = '1'));
    lastPhaseStrobe <= sharingCount_1;
    IF (dinVldSM = '1') OR (sharingCount_1 > '0') THEN 
      IF sharingCount_1 = '1' THEN 
        nextSharingCount <= '0';
      ELSE 
        add_cast := '0' & sharingCount_1;
        add_temp := add_cast + to_unsigned(16#1#, 2);
        nextSharingCount <= add_temp(0);
      END IF;
    ELSE 
      nextSharingCount <= sharingCount_1;
    END IF;
    IF dinVldSM = '1' THEN 
      IF wrCount_1 = '1' THEN 
        out4 := '0';
      ELSE 
        add_cast_0 := '0' & wrCount_1;
        add_temp_0 := add_cast_0 + to_unsigned(16#1#, 2);
        out4 := add_temp_0(0);
      END IF;
    ELSE 
      out4 := wrCount_1;
    END IF;
    IF (rdCount_1 /= out4) OR (dinVldSM = '1') THEN 
      IF rdCount_1 = '0' THEN 
        nextDelayLineRdAddr <= '1';
      ELSE 
        sub_cast := '0' & rdCount_1;
        sub_temp := sub_cast - to_unsigned(16#1#, 2);
        nextDelayLineRdAddr <= sub_temp(0);
      END IF;
    ELSE 
      nextDelayLineRdAddr <= rdCount_1;
    END IF;
    IF (sharingCount_1 > '0') OR (dinVldSM = '1') THEN 
      IF sharingCount_1 = '1' THEN 
        IF wrCount_1 = '1' THEN 
          nextDelayLineRdAddrReverse <= '0';
        ELSE 
          add_cast_2 := '0' & wrCount_1;
          add_temp_2 := add_cast_2 + to_unsigned(16#1#, 2);
          nextDelayLineRdAddrReverse <= add_temp_2(0);
        END IF;
      ELSIF rdCountReverse_1 = '1' THEN 
        nextDelayLineRdAddrReverse <= '0';
      ELSE 
        add_cast_1 := '0' & rdCountReverse_1;
        add_temp_1 := add_cast_1 + to_unsigned(16#1#, 2);
        nextDelayLineRdAddrReverse <= add_temp_1(0);
      END IF;
    ELSE 
      nextDelayLineRdAddrReverse <= rdCountReverse_1;
    END IF;
    nextDelayLineWrAddr <= out4;
  END PROCESS InputControl_output;


  delayLineShiftEn0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEnP <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEnP <= lastPhaseStrobe;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn0_process;


  delayLineShiftEn1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn1_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn1_1 <= delayLineShiftEnP;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn1_process;


  delayLineShiftEn2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn2_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn2_1 <= delayLineShiftEn1_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn2_process;


  delayLineShiftEn3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn3_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn3_1 <= delayLineShiftEn2_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn3_process;


  delayLineShiftEn4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn4_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn4_1 <= delayLineShiftEn3_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn4_process;


  delayLineShiftEn5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn5_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn5_1 <= delayLineShiftEn4_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn5_process;


  delayLineShiftEn6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn6_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn6_1 <= delayLineShiftEn5_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn6_process;


  delayLineShiftEn7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineShiftEn7_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineShiftEn7_1 <= delayLineShiftEn6_1;
      END IF;
    END IF;
  END PROCESS delayLineShiftEn7_process;


  validOutLookahead_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOutLookahead_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        validOutLookahead_reg(0) <= delayLineShiftEn7_1;
        validOutLookahead_reg(6 DOWNTO 1) <= validOutLookahead_reg(5 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS validOutLookahead_process;

  validOutLookahead_1 <= validOutLookahead_reg(6);

  vldOut_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      vldOut_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        vldOut_1 <= validOutLookahead_1;
      END IF;
    END IF;
  END PROCESS vldOut_process;


  notValid <=  NOT vldOut_1;

  rdAddr0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr0_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr0_1 <= sharingCount_1;
      END IF;
    END IF;
  END PROCESS rdAddr0_process;


  rdAddr0_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr1 <= rdAddr0_1;
      END IF;
    END IF;
  END PROCESS rdAddr0_2_process;


  rdAddr1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr2 <= rdAddr1;
      END IF;
    END IF;
  END PROCESS rdAddr1_1_process;


  rdAddr2_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr3 <= rdAddr2;
      END IF;
    END IF;
  END PROCESS rdAddr2_1_process;


  rdAddr3_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr4 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr4 <= rdAddr3;
      END IF;
    END IF;
  END PROCESS rdAddr3_1_process;


  rdAddr4_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr5 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr5 <= rdAddr4;
      END IF;
    END IF;
  END PROCESS rdAddr4_1_process;


  rdAddr5_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr6 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr6 <= rdAddr5;
      END IF;
    END IF;
  END PROCESS rdAddr5_1_process;


  rdAddr6_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdAddr7 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdAddr7 <= rdAddr6;
      END IF;
    END IF;
  END PROCESS rdAddr6_1_process;


  rdAddrEndZero <=  NOT rdAddr7;

  finalSumValidPipe_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      finalSumValidPipe_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        finalSumValidPipe_reg(0) <= rdAddrEndZero;
        finalSumValidPipe_reg(5 DOWNTO 1) <= finalSumValidPipe_reg(4 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS finalSumValidPipe_process;

  accumulate <= finalSumValidPipe_reg(5);

  accDataOut <= to_signed(0, 33);

  delayLineEnd0_signed <= signed(delayLineEnd0);

  delayLineDataIn1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn1_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn1_1 <= delayLineEnd0_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn1_process;


  delayLineEnd1_signed <= signed(delayLineEnd1);

  delayLineDataIn2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn2_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn2_1 <= delayLineEnd1_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn2_process;


  delayLineEnd2_signed <= signed(delayLineEnd2);

  delayLineDataIn3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn3_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn3_1 <= delayLineEnd2_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn3_process;


  delayLineEnd3_signed <= signed(delayLineEnd3);

  delayLineDataIn4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn4_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn4_1 <= delayLineEnd3_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn4_process;


  delayLineEnd4_signed <= signed(delayLineEnd4);

  delayLineDataIn5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn5_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn5_1 <= delayLineEnd4_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn5_process;


  delayLineEnd5_signed <= signed(delayLineEnd5);

  delayLineDataIn6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn6_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn6_1 <= delayLineEnd5_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn6_process;


  delayLineEnd6_signed <= signed(delayLineEnd6);

  delayLineDataIn7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLineDataIn7_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayLineDataIn7_1 <= delayLineEnd6_signed;
      END IF;
    END IF;
  END PROCESS delayLineDataIn7_process;


  -- Coefficient table for multiplier6
  coeffTable6_output : PROCESS (rdAddr6)
  BEGIN
    CASE rdAddr6 IS
      WHEN '0' =>
        coeffTableOut6 <= to_signed(16#05068#, 17);
      WHEN '1' =>
        coeffTableOut6 <= to_signed(16#00000#, 17);
      WHEN OTHERS => 
        coeffTableOut6 <= to_signed(16#00000#, 17);
    END CASE;
  END PROCESS coeffTable6_output;


  coeffTableRegP6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP6_1 <= coeffTableOut6;
      END IF;
    END IF;
  END PROCESS coeffTableRegP6_process;


  coeffTableReg6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg6_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg6_1 <= coeffTableRegP6_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg6_process;


  -- Coefficient table for multiplier5
  coeffTable5_output : PROCESS (rdAddr5)
  BEGIN
    CASE rdAddr5 IS
      WHEN '0' =>
        coeffTableOut5 <= to_signed(16#00BA3#, 17);
      WHEN '1' =>
        coeffTableOut5 <= to_signed(-16#01813#, 17);
      WHEN OTHERS => 
        coeffTableOut5 <= to_signed(16#00000#, 17);
    END CASE;
  END PROCESS coeffTable5_output;


  coeffTableRegP5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP5_1 <= coeffTableOut5;
      END IF;
    END IF;
  END PROCESS coeffTableRegP5_process;


  coeffTableReg5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg5_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg5_1 <= coeffTableRegP5_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg5_process;


  -- Coefficient table for multiplier4
  coeffTable4_output : PROCESS (rdAddr4)
  BEGIN
    CASE rdAddr4 IS
      WHEN '0' =>
        coeffTableOut4 <= to_signed(16#002FB#, 17);
      WHEN '1' =>
        coeffTableOut4 <= to_signed(-16#005FC#, 17);
      WHEN OTHERS => 
        coeffTableOut4 <= to_signed(16#00000#, 17);
    END CASE;
  END PROCESS coeffTable4_output;


  coeffTableRegP4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP4_1 <= coeffTableOut4;
      END IF;
    END IF;
  END PROCESS coeffTableRegP4_process;


  coeffTableReg4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg4_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg4_1 <= coeffTableRegP4_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg4_process;


  -- Coefficient table for multiplier3
  coeffTable3_output : PROCESS (rdAddr3)
  BEGIN
    CASE rdAddr3 IS
      WHEN '0' =>
        coeffTableOut3 <= to_signed(16#00093#, 17);
      WHEN '1' =>
        coeffTableOut3 <= to_signed(-16#00161#, 17);
      WHEN OTHERS => 
        coeffTableOut3 <= to_signed(16#00000#, 17);
    END CASE;
  END PROCESS coeffTable3_output;


  coeffTableRegP3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP3_1 <= coeffTableOut3;
      END IF;
    END IF;
  END PROCESS coeffTableRegP3_process;


  coeffTableReg3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg3_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg3_1 <= coeffTableRegP3_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg3_process;


  -- Coefficient table for multiplier2
  coeffTable2_output : PROCESS (rdAddr2)
  BEGIN
    CASE rdAddr2 IS
      WHEN '0' =>
        coeffTableOut2 <= to_signed(16#00011#, 17);
      WHEN '1' =>
        coeffTableOut2 <= to_signed(-16#00036#, 17);
      WHEN OTHERS => 
        coeffTableOut2 <= to_signed(16#00000#, 17);
    END CASE;
  END PROCESS coeffTable2_output;


  coeffTableRegP2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP2_1 <= coeffTableOut2;
      END IF;
    END IF;
  END PROCESS coeffTableRegP2_process;


  coeffTableReg2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg2_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg2_1 <= coeffTableRegP2_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg2_process;


  -- Coefficient table for multiplier1
  coeffTable1_output : PROCESS (rdAddr1)
  BEGIN
    CASE rdAddr1 IS
      WHEN '0' =>
        coeffTableOut1 <= to_signed(16#00001#, 17);
      WHEN '1' =>
        coeffTableOut1 <= to_signed(-16#00004#, 17);
      WHEN OTHERS => 
        coeffTableOut1 <= to_signed(16#00000#, 17);
    END CASE;
  END PROCESS coeffTable1_output;


  coeffTableRegP1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableRegP1_1 <= coeffTableOut1;
      END IF;
    END IF;
  END PROCESS coeffTableRegP1_process;


  coeffTableReg1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      coeffTableReg1_1 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffTableReg1_1 <= coeffTableRegP1_1;
      END IF;
    END IF;
  END PROCESS coeffTableReg1_process;


  sumIn <= to_signed(0, 33);

  filterDelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumOut <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sumOut <= sumIn;
      END IF;
    END IF;
  END PROCESS filterDelay_process;


  sumOut_5_signed <= signed(sumOut_5);

  sumOutReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumOutReg_1 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sumOutReg_1 <= sumOut_5_signed;
      END IF;
    END IF;
  END PROCESS sumOutReg_process;


  
  accSwitchOut <= accDataOut_1 WHEN accumulate = '0' ELSE
      accDataOut;

  accAdderOut <= accSwitchOut + sumOutReg_1;

  accDataOut_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accDataOut_1 <= to_signed(0, 33);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        accDataOut_1 <= accAdderOut;
      END IF;
    END IF;
  END PROCESS accDataOut_2_process;


  converterOut <= resize(accDataOut_1, 34);

  dout_re_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dout_re_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND validOutLookahead_1 = '1' THEN
        dout_re_1 <= converterOut;
      END IF;
    END IF;
  END PROCESS dout_re_process;


  dataZero <= to_signed(0, 34);

  
  subfilterOutTmp_1_tmp <= dout_re_1 WHEN notValid = '0' ELSE
      dataZero;

  subfilterOutTmp_1 <= std_logic_vector(subfilterOutTmp_1_tmp);

END rtl;

