-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\gcSection.vhd
-- Created: 2026-01-30 10:42:36
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: gcSection
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/CICDecimation/gcSection
-- Hierarchy Level: 2
-- Model version: 17.88
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DECIMATOR_pkg.ALL;

ENTITY gcSection IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        combOut_re                        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_E5
        combOut_im                        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_E5
        internalReset                     :   IN    std_logic;
        gcOut_re                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END gcSection;


ARCHITECTURE rtl OF gcSection IS

  -- Signals
  SIGNAL combOut_re_signed                : signed(17 DOWNTO 0);  -- sfix18_E5
  SIGNAL bShift_re                        : signed(15 DOWNTO 0);  -- sfix16_E7
  SIGNAL bShiftreg_re                     : signed(36 DOWNTO 0);  -- sfix37_En14
  SIGNAL bRShift_re                       : signed(36 DOWNTO 0);  -- sfix37_En14
  SIGNAL coarseGtmpreg_re                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL combOut_im_signed                : signed(17 DOWNTO 0);  -- sfix18_E5
  SIGNAL bShift_im                        : signed(15 DOWNTO 0);  -- sfix16_E7
  SIGNAL bShiftreg_im                     : signed(36 DOWNTO 0);  -- sfix37_En14
  SIGNAL bRShift_im                       : signed(36 DOWNTO 0);  -- sfix37_En14
  SIGNAL coarseGtmpreg_im                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL fineMultreg                      : signed(22 DOWNTO 0);  -- sfix23_En21
  SIGNAL gainCorrection_gainDatareg2_re   : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL gainCorrection_gainDatareg1_im   : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL gainCorrection_gainDatareg2_im   : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL gainCorrection_gainOutareg1_re   : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL gainCorrection_gainOutareg1_im   : signed(38 DOWNTO 0);  -- sfix39
  SIGNAL gainCorrection_gainDatareg1_re   : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL gainCorrection_fineGreg_tmp2     : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL mulOut_re                        : signed(38 DOWNTO 0);  -- sfix39_En35
  SIGNAL mulOut_im                        : signed(38 DOWNTO 0);  -- sfix39_En35
  SIGNAL intdelay_reg                     : vector_of_signed39(0 TO 2);  -- sfix39 [3]
  SIGNAL mulOutreg_re                     : signed(38 DOWNTO 0);  -- sfix39_En35
  SIGNAL gcOutreg_re                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL intdelay_reg_1                   : vector_of_signed16(0 TO 1);  -- sfix16 [2]
  SIGNAL gcOut_re_tmp                     : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  combOut_re_signed <= signed(combOut_re);

  
  bShift_re <= X"7FFF" WHEN (combOut_re_signed(17) = '0') AND (combOut_re_signed(16 DOWNTO 2) = "111111111111111") ELSE
      combOut_re_signed(17 DOWNTO 2) + ('0' & combOut_re_signed(1));

  bShiftreg_re <= bShift_re & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  bRShift_re <= SHIFT_RIGHT(bShiftreg_re, 21);

  
  coarseGtmpreg_re <= X"7FFF" WHEN (bRShift_re(36) = '0') AND (bRShift_re(35 DOWNTO 15) /= "000000000000000000000") ELSE
      X"8000" WHEN (bRShift_re(36) = '1') AND (bRShift_re(35 DOWNTO 15) /= "111111111111111111111") ELSE
      bRShift_re(15 DOWNTO 0);

  combOut_im_signed <= signed(combOut_im);

  
  bShift_im <= X"7FFF" WHEN (combOut_im_signed(17) = '0') AND (combOut_im_signed(16 DOWNTO 2) = "111111111111111") ELSE
      combOut_im_signed(17 DOWNTO 2) + ('0' & combOut_im_signed(1));

  bShiftreg_im <= bShift_im & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  bRShift_im <= SHIFT_RIGHT(bShiftreg_im, 21);

  
  coarseGtmpreg_im <= X"7FFF" WHEN (bRShift_im(36) = '0') AND (bRShift_im(35 DOWNTO 15) /= "000000000000000000000") ELSE
      X"8000" WHEN (bRShift_im(36) = '1') AND (bRShift_im(35 DOWNTO 15) /= "111111111111111111111") ELSE
      bRShift_im(15 DOWNTO 0);

  fineMultreg <= to_signed(16#200000#, 23);

  gainCorrection_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gainCorrection_gainDatareg1_re <= to_signed(16#0000#, 16);
      gainCorrection_gainDatareg1_im <= to_signed(16#0000#, 16);
      gainCorrection_gainDatareg2_re <= to_signed(16#0000#, 16);
      gainCorrection_gainDatareg2_im <= to_signed(16#0000#, 16);
      gainCorrection_gainOutareg1_re <= to_signed(0, 39);
      gainCorrection_gainOutareg1_im <= to_signed(0, 39);
      mulOut_re <= to_signed(0, 39);
      mulOut_im <= to_signed(0, 39);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          gainCorrection_gainDatareg1_re <= to_signed(16#0000#, 16);
          gainCorrection_gainDatareg1_im <= to_signed(16#0000#, 16);
          gainCorrection_gainDatareg2_re <= to_signed(16#0000#, 16);
          gainCorrection_gainDatareg2_im <= to_signed(16#0000#, 16);
          gainCorrection_gainOutareg1_re <= to_signed(0, 39);
          gainCorrection_gainOutareg1_im <= to_signed(0, 39);
          mulOut_re <= to_signed(0, 39);
          mulOut_im <= to_signed(0, 39);
        ELSE 
          mulOut_re <= gainCorrection_gainOutareg1_re;
          mulOut_im <= gainCorrection_gainOutareg1_im;
          gainCorrection_gainDatareg1_re <= gainCorrection_gainDatareg2_re;
          gainCorrection_gainDatareg2_re <= coarseGtmpreg_re;
          gainCorrection_gainDatareg1_im <= gainCorrection_gainDatareg2_im;
          gainCorrection_gainDatareg2_im <= coarseGtmpreg_im;
          gainCorrection_gainOutareg1_re <= resize(gainCorrection_gainDatareg1_re & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 39);
          gainCorrection_gainOutareg1_im <= resize(gainCorrection_gainDatareg1_im & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 39);
        END IF;
      END IF;
    END IF;
  END PROCESS gainCorrection_process;

  gainCorrection_fineGreg_tmp2 <= fineMultreg;

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg <= (OTHERS => to_signed(0, 39));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg(0) <= mulOut_re;
        intdelay_reg(1 TO 2) <= intdelay_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS intdelay_process;

  mulOutreg_re <= intdelay_reg(2);

  
  gcOutreg_re <= X"7FFF" WHEN ((mulOutreg_re(38) = '0') AND (mulOutreg_re(37 DOWNTO 36) /= "00")) OR ((mulOutreg_re(38) = '0') AND (mulOutreg_re(36 DOWNTO 21) = X"7FFF")) ELSE
      X"8000" WHEN (mulOutreg_re(38) = '1') AND (mulOutreg_re(37 DOWNTO 36) /= "11") ELSE
      mulOutreg_re(36 DOWNTO 21) + ('0' & mulOutreg_re(20));

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg_1 <= (OTHERS => to_signed(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg_1(0) <= gcOutreg_re;
        intdelay_reg_1(1) <= intdelay_reg_1(0);
      END IF;
    END IF;
  END PROCESS intdelay_1_process;

  gcOut_re_tmp <= intdelay_reg_1(1);

  gcOut_re <= std_logic_vector(gcOut_re_tmp);

END rtl;

