-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\HBF1.vhd
-- Created: 2026-01-26 17:17:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HBF1
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1
-- Hierarchy Level: 1
-- Model version: 17.86
-- 
-- HDL FIR Decimation
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DECIMATOR_pkg.ALL;

ENTITY HBF1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(32 DOWNTO 0);  -- sfix33_En30
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(65 DOWNTO 0);  -- sfix66_En62
        validOut                          :   OUT   std_logic
        );
END HBF1;


ARCHITECTURE rtl OF HBF1 IS

  -- Component Declarations
  COMPONENT partlySerialCtrl
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          validIn                         :   IN    std_logic;
          ctrl                            :   OUT   std_logic;
          ready                           :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT FIRPartlySerial
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterInput                     :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          ctrl                            :   IN    std_logic;
          subfilterOutTmp_1               :   OUT   std_logic_vector(67 DOWNTO 0)  -- sfix68_En63
          );
  END COMPONENT;

  COMPONENT FIRPartlySerial_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterInput                     :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En30
          ctrl                            :   IN    std_logic;
          subfilterOutTmp_2               :   OUT   std_logic_vector(67 DOWNTO 0);  -- sfix68_En63
          subfilterOutTmp_vld2            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT sumTree_firdecim
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          accIn                           :   IN    vector_of_std_logic_vector68(0 TO 1);  -- sfix68_En63 [2]
          subfilterOut_vld2               :   IN    std_logic;
          accOut                          :   OUT   std_logic_vector(65 DOWNTO 0);  -- sfix66_En62
          accOutVld                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : partlySerialCtrl
    USE ENTITY work.partlySerialCtrl(rtl);

  FOR ALL : FIRPartlySerial
    USE ENTITY work.FIRPartlySerial(rtl);

  FOR ALL : FIRPartlySerial_block
    USE ENTITY work.FIRPartlySerial_block(rtl);

  FOR ALL : sumTree_firdecim
    USE ENTITY work.sumTree_firdecim(rtl);

  -- Signals
  SIGNAL syncReset                        : std_logic;
  SIGNAL ctrl                             : std_logic;
  SIGNAL ready                            : std_logic;
  SIGNAL vldAndRdy                        : std_logic;
  SIGNAL dataIn_signed                    : signed(32 DOWNTO 0);  -- sfix33_En30
  SIGNAL dataIn_cast                      : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL delayLine                        : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL vldAndRdy_1                      : std_logic;
  SIGNAL delayLine_1                      : signed(33 DOWNTO 0);  -- sfix34_En30
  SIGNAL subfilterOutTmp_vld2             : std_logic;
  SIGNAL accIn                            : vector_of_std_logic_vector68(0 TO 1);  -- ufix68 [2]
  SIGNAL accOut                           : std_logic_vector(65 DOWNTO 0);  -- ufix66
  SIGNAL accOutVld                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(65 DOWNTO 0);  -- sfix66_En62
  SIGNAL accOut_signed                    : signed(65 DOWNTO 0);  -- sfix66_En62
  SIGNAL muxOut                           : signed(65 DOWNTO 0);  -- sfix66_En62
  SIGNAL dataOut_tmp                      : signed(65 DOWNTO 0);  -- sfix66_En62

BEGIN
  u_partlySerialCtrl : partlySerialCtrl
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              validIn => validIn,
              ctrl => ctrl,
              ready => ready
              );

  u_FIRDecim_phase_1 : FIRPartlySerial
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              filterInput => std_logic_vector(delayLine),  -- sfix34_En30
              ctrl => ctrl,
              subfilterOutTmp_1 => accIn(0)  -- sfix68_En63
              );

  u_FIRDecim_phase_2 : FIRPartlySerial_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              filterInput => std_logic_vector(delayLine_1),  -- sfix34_En30
              ctrl => ctrl,
              subfilterOutTmp_2 => accIn(1),  -- sfix68_En63
              subfilterOutTmp_vld2 => subfilterOutTmp_vld2
              );

  u_FirDecimAccum_2 : sumTree_firdecim
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              accIn => accIn,  -- sfix68_En63 [2]
              subfilterOut_vld2 => subfilterOutTmp_vld2,
              accOut => accOut,  -- sfix66_En62
              accOutVld => accOutVld
              );

  syncReset <= '0';

  vldAndRdy <= validIn AND ready;

  dataIn_signed <= signed(dataIn);

  dataIn_cast <= resize(dataIn_signed, 34);

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLine <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          delayLine <= to_signed(0, 34);
        ELSIF vldAndRdy = '1' THEN
          delayLine <= dataIn_cast;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  vldAndRdy_1 <= validIn AND ready;

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayLine_1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          delayLine_1 <= to_signed(0, 34);
        ELSIF vldAndRdy_1 = '1' THEN
          delayLine_1 <= delayLine;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;



  ZERO_OUT <= to_signed(0, 66);

  accOut_signed <= signed(accOut);

  
  muxOut <= ZERO_OUT WHEN accOutVld = '0' ELSE
      accOut_signed;

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataOut_tmp <= to_signed(0, 66);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dataOut_tmp <= to_signed(0, 66);
        ELSE 
          dataOut_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  dataOut <= std_logic_vector(dataOut_tmp);

  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          validOut <= '0';
        ELSE 
          validOut <= accOutVld;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


END rtl;

