-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\iSection.vhd
-- Created: 2026-01-30 11:58:51
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: iSection
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/CICDecimation/iSection
-- Hierarchy Level: 2
-- Model version: 17.90
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY iSection IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataInreg                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validInreg                        :   IN    std_logic;
        internalReset                     :   IN    std_logic;
        integOut_re                       :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23
        integOut_im                       :   OUT   std_logic_vector(22 DOWNTO 0)  -- sfix23
        );
END iSection;


ARCHITECTURE rtl OF iSection IS

  -- Signals
  SIGNAL dataInreg_signed                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL iIn_re1                          : signed(34 DOWNTO 0);  -- sfix35_En12
  SIGNAL iOut_re1                         : signed(34 DOWNTO 0);  -- sfix35_En12
  SIGNAL adder_add_cast                   : signed(35 DOWNTO 0);  -- sfix36_En12
  SIGNAL adder_add_cast_1                 : signed(35 DOWNTO 0);  -- sfix36_En12
  SIGNAL addOut_re1                       : signed(35 DOWNTO 0);  -- sfix36_En12
  SIGNAL iOutreg_re1                      : signed(35 DOWNTO 0);  -- sfix36_En12
  SIGNAL iIn_re2                          : signed(27 DOWNTO 0);  -- sfix28_En5
  SIGNAL iOut_re2                         : signed(27 DOWNTO 0);  -- sfix28_En5
  SIGNAL adder_add_cast_2                 : signed(28 DOWNTO 0);  -- sfix29_En5
  SIGNAL adder_add_cast_3                 : signed(28 DOWNTO 0);  -- sfix29_En5
  SIGNAL addOut_re2                       : signed(28 DOWNTO 0);  -- sfix29_En5
  SIGNAL iOutreg_re2                      : signed(28 DOWNTO 0);  -- sfix29_En5
  SIGNAL iIn_re3                          : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL iOut_re3                         : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL addOut_re3                       : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOutreg_re3                      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL dtc_im                           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL iIn_im1                          : signed(34 DOWNTO 0);  -- sfix35_En12
  SIGNAL iOut_im1                         : signed(34 DOWNTO 0);  -- sfix35_En12
  SIGNAL adder_add_cast_4                 : signed(35 DOWNTO 0);  -- sfix36_En12
  SIGNAL adder_add_cast_5                 : signed(35 DOWNTO 0);  -- sfix36_En12
  SIGNAL addOut_im1                       : signed(35 DOWNTO 0);  -- sfix36_En12
  SIGNAL iOutreg_im1                      : signed(35 DOWNTO 0);  -- sfix36_En12
  SIGNAL iIn_im2                          : signed(27 DOWNTO 0);  -- sfix28_En5
  SIGNAL iOut_im2                         : signed(27 DOWNTO 0);  -- sfix28_En5
  SIGNAL adder_add_cast_6                 : signed(28 DOWNTO 0);  -- sfix29_En5
  SIGNAL adder_add_cast_7                 : signed(28 DOWNTO 0);  -- sfix29_En5
  SIGNAL addOut_im2                       : signed(28 DOWNTO 0);  -- sfix29_En5
  SIGNAL iOutreg_im2                      : signed(28 DOWNTO 0);  -- sfix29_En5
  SIGNAL iIn_im3                          : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL iOut_im3                         : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL addOut_im3                       : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOutreg_im3                      : signed(23 DOWNTO 0);  -- sfix24

BEGIN
  dataInreg_signed <= signed(dataInreg);

  iIn_re1 <= resize(dataInreg_signed(15 DOWNTO 2), 35);

  adder_add_cast <= resize(iIn_re1, 36);
  adder_add_cast_1 <= resize(iOut_re1, 36);
  addOut_re1 <= adder_add_cast + adder_add_cast_1;

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_re1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_re1 <= to_signed(0, 36);
        ELSIF validInreg = '1' THEN
          iOutreg_re1 <= addOut_re1;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  iOut_re1 <= iOutreg_re1(34 DOWNTO 0);

  iIn_re2 <= iOut_re1(34 DOWNTO 7);

  adder_add_cast_2 <= resize(iIn_re2, 29);
  adder_add_cast_3 <= resize(iOut_re2, 29);
  addOut_re2 <= adder_add_cast_2 + adder_add_cast_3;

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_re2 <= to_signed(16#00000000#, 29);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_re2 <= to_signed(16#00000000#, 29);
        ELSIF validInreg = '1' THEN
          iOutreg_re2 <= addOut_re2;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  iOut_re2 <= iOutreg_re2(27 DOWNTO 0);

  iIn_re3 <= iOut_re2(27 DOWNTO 5);

  addOut_re3 <= resize(iIn_re3, 24) + resize(iOut_re3, 24);

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_re3 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_re3 <= to_signed(16#000000#, 24);
        ELSIF validInreg = '1' THEN
          iOutreg_re3 <= addOut_re3;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  iOut_re3 <= iOutreg_re3(22 DOWNTO 0);

  integOut_re <= std_logic_vector(iOut_re3);

  dtc_im <= to_signed(16#0000#, 16);

  iIn_im1 <= resize(dtc_im(15 DOWNTO 2), 35);

  adder_add_cast_4 <= resize(iIn_im1, 36);
  adder_add_cast_5 <= resize(iOut_im1, 36);
  addOut_im1 <= adder_add_cast_4 + adder_add_cast_5;

  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_im1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_im1 <= to_signed(0, 36);
        ELSIF validInreg = '1' THEN
          iOutreg_im1 <= addOut_im1;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


  iOut_im1 <= iOutreg_im1(34 DOWNTO 0);

  iIn_im2 <= iOut_im1(34 DOWNTO 7);

  adder_add_cast_6 <= resize(iIn_im2, 29);
  adder_add_cast_7 <= resize(iOut_im2, 29);
  addOut_im2 <= adder_add_cast_6 + adder_add_cast_7;

  intdelay_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_im2 <= to_signed(16#00000000#, 29);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_im2 <= to_signed(16#00000000#, 29);
        ELSIF validInreg = '1' THEN
          iOutreg_im2 <= addOut_im2;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_4_process;


  iOut_im2 <= iOutreg_im2(27 DOWNTO 0);

  iIn_im3 <= iOut_im2(27 DOWNTO 5);

  addOut_im3 <= resize(iIn_im3, 24) + resize(iOut_im3, 24);

  intdelay_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_im3 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_im3 <= to_signed(16#000000#, 24);
        ELSIF validInreg = '1' THEN
          iOutreg_im3 <= addOut_im3;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_5_process;


  iOut_im3 <= iOutreg_im3(22 DOWNTO 0);

  integOut_im <= std_logic_vector(iOut_im3);

END rtl;

