-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\iSection.vhd
-- Created: 2026-01-30 10:42:36
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: iSection
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/CICDecimation/iSection
-- Hierarchy Level: 2
-- Model version: 17.88
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY iSection IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataInreg                         :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2
        validInreg                        :   IN    std_logic;
        internalReset                     :   IN    std_logic;
        integOut_re                       :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23
        integOut_im                       :   OUT   std_logic_vector(22 DOWNTO 0)  -- sfix23
        );
END iSection;


ARCHITECTURE rtl OF iSection IS

  -- Signals
  SIGNAL dataInreg_signed                 : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL iIn_re1                          : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL iOut_re1                         : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL addOut_re1                       : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOutreg_re1                      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOut_re2                         : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL addOut_re2                       : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOutreg_re2                      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOut_re3                         : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL addOut_re3                       : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOutreg_re3                      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL dtc_im                           : signed(1 DOWNTO 0);  -- sfix2
  SIGNAL iIn_im1                          : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL iOut_im1                         : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL addOut_im1                       : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOutreg_im1                      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOut_im2                         : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL addOut_im2                       : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOutreg_im2                      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOut_im3                         : signed(22 DOWNTO 0);  -- sfix23
  SIGNAL addOut_im3                       : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL iOutreg_im3                      : signed(23 DOWNTO 0);  -- sfix24

BEGIN
  dataInreg_signed <= signed(dataInreg);

  iIn_re1 <= resize(dataInreg_signed, 23);

  addOut_re1 <= resize(iIn_re1, 24) + resize(iOut_re1, 24);

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_re1 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_re1 <= to_signed(16#000000#, 24);
        ELSIF validInreg = '1' THEN
          iOutreg_re1 <= addOut_re1;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  iOut_re1 <= iOutreg_re1(22 DOWNTO 0);

  addOut_re2 <= resize(iOut_re1, 24) + resize(iOut_re2, 24);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_re2 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_re2 <= to_signed(16#000000#, 24);
        ELSIF validInreg = '1' THEN
          iOutreg_re2 <= addOut_re2;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  iOut_re2 <= iOutreg_re2(22 DOWNTO 0);

  addOut_re3 <= resize(iOut_re2, 24) + resize(iOut_re3, 24);

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_re3 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_re3 <= to_signed(16#000000#, 24);
        ELSIF validInreg = '1' THEN
          iOutreg_re3 <= addOut_re3;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  iOut_re3 <= iOutreg_re3(22 DOWNTO 0);

  integOut_re <= std_logic_vector(iOut_re3);

  dtc_im <= to_signed(16#0#, 2);

  iIn_im1 <= resize(dtc_im, 23);

  addOut_im1 <= resize(iIn_im1, 24) + resize(iOut_im1, 24);

  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_im1 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_im1 <= to_signed(16#000000#, 24);
        ELSIF validInreg = '1' THEN
          iOutreg_im1 <= addOut_im1;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


  iOut_im1 <= iOutreg_im1(22 DOWNTO 0);

  addOut_im2 <= resize(iOut_im1, 24) + resize(iOut_im2, 24);

  intdelay_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_im2 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_im2 <= to_signed(16#000000#, 24);
        ELSIF validInreg = '1' THEN
          iOutreg_im2 <= addOut_im2;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_4_process;


  iOut_im2 <= iOutreg_im2(22 DOWNTO 0);

  addOut_im3 <= resize(iOut_im2, 24) + resize(iOut_im3, 24);

  intdelay_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      iOutreg_im3 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF internalReset = '1' THEN
          iOutreg_im3 <= to_signed(16#000000#, 24);
        ELSIF validInreg = '1' THEN
          iOutreg_im3 <= addOut_im3;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_5_process;


  iOut_im3 <= iOutreg_im3(22 DOWNTO 0);

  integOut_im <= std_logic_vector(iOut_im3);

END rtl;

