-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\sumTree_firdecim.vhd
-- Created: 2026-01-26 17:17:42
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sumTree_firdecim
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/sumTree_firdecim
-- Hierarchy Level: 2
-- Model version: 17.86
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DECIMATOR_pkg.ALL;

ENTITY sumTree_firdecim IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        accIn                             :   IN    vector_of_std_logic_vector68(0 TO 1);  -- sfix68_En63 [2]
        subfilterOut_vld2                 :   IN    std_logic;
        accOut                            :   OUT   std_logic_vector(65 DOWNTO 0);  -- sfix66_En62
        accOutVld                         :   OUT   std_logic
        );
END sumTree_firdecim;


ARCHITECTURE rtl OF sumTree_firdecim IS

  -- Signals
  SIGNAL accIn_0                          : signed(67 DOWNTO 0);  -- sfix68_En63
  SIGNAL accIn_1                          : signed(67 DOWNTO 0);  -- sfix68_En63
  SIGNAL accS_1                           : signed(67 DOWNTO 0);  -- sfix68_En63
  SIGNAL accReg_1                         : signed(67 DOWNTO 0);  -- sfix68_En63
  SIGNAL dout_cast                        : signed(65 DOWNTO 0);  -- sfix66_En62
  SIGNAL accOut_tmp                       : signed(65 DOWNTO 0);  -- sfix66_En62
  SIGNAL intdelay_reg                     : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]

BEGIN
  accIn_0 <= signed(accIn(0));

  accIn_1 <= signed(accIn(1));

  accS_1 <= accIn_0 + accIn_1;

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accReg_1 <= to_signed(0, 68);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        accReg_1 <= accS_1;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  dout_cast <= accReg_1(66 DOWNTO 1);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accOut_tmp <= to_signed(0, 66);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        accOut_tmp <= dout_cast;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  accOut <= std_logic_vector(accOut_tmp);

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg(0) <= subfilterOut_vld2;
        intdelay_reg(1) <= intdelay_reg(0);
      END IF;
    END IF;
  END PROCESS intdelay_2_process;

  accOutVld <= intdelay_reg(1);

END rtl;

