-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\Addressable_Delay_Line_block4.vhd
-- Created: 2026-01-30 11:58:51
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Addressable_Delay_Line_block4
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/FIRPartlySerial/Addressable Delay Line
-- Hierarchy Level: 3
-- Model version: 17.90
-- 
-- Addressable Delay Line
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Addressable_Delay_Line_block4 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En13
        validIn                           :   IN    std_logic;
        rdAddr                            :   IN    std_logic;  -- ufix1
        dataOut                           :   OUT   std_logic_vector(16 DOWNTO 0)  -- sfix17_En13
        );
END Addressable_Delay_Line_block4;


ARCHITECTURE rtl OF Addressable_Delay_Line_block4 IS

  -- Signals
  SIGNAL rdCompare                        : std_logic;
  SIGNAL dataIn_signed                    : signed(16 DOWNTO 0);  -- sfix17_En13
  SIGNAL delayedSignals0                  : signed(16 DOWNTO 0);  -- sfix17_En13
  SIGNAL ZEROCONST                        : signed(16 DOWNTO 0);  -- sfix17_En13
  SIGNAL switchDataOut                    : signed(16 DOWNTO 0);  -- sfix17_En13
  SIGNAL dataOut_tmp                      : signed(16 DOWNTO 0);  -- sfix17_En13

BEGIN
  
  rdCompare <= '1' WHEN rdAddr > '0' ELSE
      '0';

  dataIn_signed <= signed(dataIn);

  delay0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayedSignals0 <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND validIn = '1' THEN
        delayedSignals0 <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS delay0_process;


  ZEROCONST <= to_signed(16#00000#, 17);

  
  switchDataOut <= delayedSignals0 WHEN rdCompare = '0' ELSE
      ZEROCONST;

  dataOutReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataOut_tmp <= to_signed(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dataOut_tmp <= switchDataOut;
      END IF;
    END IF;
  END PROCESS dataOutReg_process;


  dataOut <= std_logic_vector(dataOut_tmp);

END rtl;

