-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\DECIMATOR.vhd
-- Created: 2026-01-30 11:58:51
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-06
-- Target subsystem base rate: 1e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out2                          ce_out        1e-06
-- Out1                          ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DECIMATOR
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR
-- Hierarchy Level: 0
-- Model version: 17.90
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DECIMATOR IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        In2                               :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out2                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out1                              :   OUT   std_logic
        );
END DECIMATOR;


ARCHITECTURE rtl OF DECIMATOR IS

  -- Component Declarations
  COMPONENT CICDecimation
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT DCF
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT HBF1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT HBF2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : CICDecimation
    USE ENTITY work.CICDecimation(rtl);

  FOR ALL : DCF
    USE ENTITY work.DCF(rtl);

  FOR ALL : HBF1
    USE ENTITY work.HBF1(rtl);

  FOR ALL : HBF2
    USE ENTITY work.HBF2(rtl);

  -- Signals
  SIGNAL CIC_Decimator_out1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL CIC_Decimator_out2               : std_logic;
  SIGNAL DCF_out1                         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL DCF_out2                         : std_logic;
  SIGNAL HBF1_out1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL HBF1_out2                        : std_logic;
  SIGNAL HBF2_out1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL HBF2_out2                        : std_logic;

BEGIN
  -- StartHere
  u_CIC_Decimator_inst : CICDecimation
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => In1,  -- sfix16_En14
              validIn => In2,
              dataOut => CIC_Decimator_out1,  -- sfix16_En14
              validOut => CIC_Decimator_out2
              );

  u_DCF : DCF
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => CIC_Decimator_out1,  -- sfix16_En14
              validIn => CIC_Decimator_out2,
              dataOut => DCF_out1,  -- sfix16_En13
              validOut => DCF_out2
              );

  u_HBF1 : HBF1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => DCF_out1,  -- sfix16_En13
              validIn => DCF_out2,
              dataOut => HBF1_out1,  -- sfix16_En12
              validOut => HBF1_out2
              );

  u_HBF2 : HBF2
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => HBF1_out1,  -- sfix16_En12
              validIn => HBF1_out2,
              dataOut => HBF2_out1,  -- sfix16_En11
              validOut => HBF2_out2
              );

  ce_out <= clk_enable;

  Out2 <= HBF2_out1;

  Out1 <= HBF2_out2;

END rtl;

