-- -------------------------------------------------------------
-- 
-- File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\VHDL\dsm_l2_sim_deci_cic_HDLgeneration\subFilter.vhd
-- Created: 2026-01-30 11:58:51
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: subFilter
-- Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/DCF/Filter/subFilter
-- Hierarchy Level: 3
-- Model version: 17.90
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DECIMATOR_pkg.ALL;

ENTITY subFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        coefIn                            :   IN    vector_of_std_logic_vector16(0 TO 12);  -- sfix16_En16 [13]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
        doutVld                           :   OUT   std_logic
        );
END subFilter;


ARCHITECTURE rtl OF subFilter IS

  -- Component Declarations
  COMPONENT FilterTapSystolicPreAddWvlIn
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dinPreAdd                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          coefIn_0                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En16
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En30
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En30
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterTapSystolicPreAddWvlIn
    USE ENTITY work.FilterTapSystolicPreAddWvlIn(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(10 DOWNTO 0);  -- ufix1 [11]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL addin                            : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL dinPreAdd                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dinDly2                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dinDly2_signed                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dinDly2_1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout                           : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_2                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_1                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_3                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_2                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_4                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_3                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_5                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_4                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_5                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL ZERO                             : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dinDly2deadOut                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_6                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_signed                    : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL dout_cast                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL muxOut                           : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL dout_1_re_tmp                    : signed(15 DOWNTO 0);  -- sfix16_En13

BEGIN
  u_FilterTap_1 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(0),  -- sfix16_En16
              addin => std_logic_vector(addin),  -- sfix48_En30
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_1,  -- sfix16_En14
              tapout => tapout  -- sfix48_En30
              );

  u_FilterTap_2 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => dinDly2_1,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(1),  -- sfix16_En16
              addin => tapout,  -- sfix48_En30
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_2,  -- sfix16_En14
              tapout => tapout_1  -- sfix48_En30
              );

  u_FilterTap_3 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => dinDly2_2,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(2),  -- sfix16_En16
              addin => tapout_1,  -- sfix48_En30
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_3,  -- sfix16_En14
              tapout => tapout_2  -- sfix48_En30
              );

  u_FilterTap_4 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => dinDly2_3,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(3),  -- sfix16_En16
              addin => tapout_2,  -- sfix48_En30
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_4,  -- sfix16_En14
              tapout => tapout_3  -- sfix48_En30
              );

  u_FilterTap_5 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => dinDly2_4,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(4),  -- sfix16_En16
              addin => tapout_3,  -- sfix48_En30
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_5,  -- sfix16_En14
              tapout => tapout_4  -- sfix48_En30
              );

  u_FilterTap_6 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => dinDly2_5,  -- sfix16_En14
              dinPreAdd => std_logic_vector(dinPreAdd),  -- sfix16_En14
              coefIn_0 => coefIn(5),  -- sfix16_En16
              addin => tapout_4,  -- sfix48_En30
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix16_En14
              tapout => tapout_5  -- sfix48_En30
              );

  u_FilterTap_7 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => dinDly2,  -- sfix16_En14
              dinPreAdd => std_logic_vector(ZERO),  -- sfix16_En14
              coefIn_0 => coefIn(6),  -- sfix16_En16
              addin => tapout_5,  -- sfix48_En30
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2deadOut,  -- sfix16_En14
              tapout => tapout_6  -- sfix48_En30
              );

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(10 DOWNTO 1) <= intdelay_reg(9 DOWNTO 0);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(10);

  vldOutTmp <= dinRegVld AND vldShift;

  ZERO_OUT <= to_signed(16#0000#, 16);

  addin <= to_signed(0, 48);

  dinDly2_signed <= signed(dinDly2);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dinPreAdd <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dinPreAdd <= to_signed(16#0000#, 16);
        ELSIF dinRegVld = '1' THEN
          dinPreAdd <= dinDly2_signed;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  ZERO <= to_signed(16#0000#, 16);

  tapout_signed <= signed(tapout_6);

  dout_cast <= tapout_signed(32 DOWNTO 17);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      dout_cast;

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dout_1_re_tmp <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(16#0000#, 16);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      doutVld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          doutVld <= '0';
        ELSE 
          doutVld <= vldOutTmp;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


END rtl;

