// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\FilterCoef.v
// Created: 2026-01-30 11:58:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterCoef
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/DCF/Filter/FilterCoef
// Hierarchy Level: 3
// Model version: 17.90
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterCoef
          (CoefOut_0,
           CoefOut_1,
           CoefOut_2,
           CoefOut_3,
           CoefOut_4,
           CoefOut_5,
           CoefOut_6);


  output  signed [15:0] CoefOut_0;  // sfix16_En16
  output  signed [15:0] CoefOut_1;  // sfix16_En16
  output  signed [15:0] CoefOut_2;  // sfix16_En16
  output  signed [15:0] CoefOut_3;  // sfix16_En16
  output  signed [15:0] CoefOut_4;  // sfix16_En16
  output  signed [15:0] CoefOut_5;  // sfix16_En16
  output  signed [15:0] CoefOut_6;  // sfix16_En16


  wire signed [15:0] CoefData;  // sfix16_En16
  wire signed [15:0] CoefData_1;  // sfix16_En16
  wire signed [15:0] CoefData_2;  // sfix16_En16
  wire signed [15:0] CoefData_3;  // sfix16_En16
  wire signed [15:0] CoefData_4;  // sfix16_En16
  wire signed [15:0] CoefData_5;  // sfix16_En16
  wire signed [15:0] CoefData_6;  // sfix16_En16


  // CoefReg_1
  assign CoefData = 16'sb0000001001011101;

  assign CoefOut_0 = CoefData;

  // CoefReg_2
  assign CoefData_1 = 16'sb0000001011111010;

  assign CoefOut_1 = CoefData_1;

  // CoefReg_3
  assign CoefData_2 = 16'sb1111011110100110;

  assign CoefOut_2 = CoefData_2;

  // CoefReg_4
  assign CoefData_3 = 16'sb1110110100110001;

  assign CoefOut_3 = CoefData_3;

  // CoefReg_5
  assign CoefData_4 = 16'sb0000101010110110;

  assign CoefOut_4 = CoefData_4;

  // CoefReg_6
  assign CoefData_5 = 16'sb0100111110101000;

  assign CoefOut_5 = CoefData_5;

  // CoefReg_7
  assign CoefData_6 = 16'sb0111011001110100;

  assign CoefOut_6 = CoefData_6;

endmodule  // FilterCoef

