// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\sumTree_firdecim.v
// Created: 2026-01-30 11:58:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: sumTree_firdecim
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/sumTree_firdecim
// Hierarchy Level: 2
// Model version: 17.90
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module sumTree_firdecim
          (clk,
           reset,
           enb,
           accIn_0,
           accIn_1,
           subfilterOut_vld2,
           accOut,
           accOutVld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [33:0] accIn_0;  // sfix34_En29
  input   signed [33:0] accIn_1;  // sfix34_En29
  input   subfilterOut_vld2;
  output  signed [15:0] accOut;  // sfix16_En12
  output  accOutVld;


  wire signed [33:0] accS_1;  // sfix34_En29
  reg signed [33:0] accReg_1;  // sfix34_En29
  wire signed [15:0] dout_cast;  // sfix16_En12
  reg signed [15:0] accOut_1;  // sfix16_En12
  reg  [1:0] intdelay_reg;  // ufix1 [2]


  assign accS_1 = accIn_0 + accIn_1;

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        accReg_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          accReg_1 <= accS_1;
        end
      end
    end

  assign dout_cast = accReg_1[32:17];

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        accOut_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          accOut_1 <= dout_cast;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        intdelay_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          intdelay_reg[0] <= subfilterOut_vld2;
          intdelay_reg[1] <= intdelay_reg[0];
        end
      end
    end

  assign accOutVld = intdelay_reg[1];

  assign accOut = accOut_1;

endmodule  // sumTree_firdecim

