// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\Addressable_Delay_Line_block7.v
// Created: 2026-01-30 10:39:16
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Addressable_Delay_Line_block7
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF2/FIRPartlySerial/Addressable_Delay_Line
// Hierarchy Level: 3
// Model version: 17.87
// 
// Addressable Delay Line
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Addressable_Delay_Line_block7
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           lutaddr,
           delayLineEnd,
           dataOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [16:0] dataIn;  // sfix17_En12
  input   validIn;
  input   lutaddr;  // ufix1
  output  signed [16:0] delayLineEnd;  // sfix17_En12
  output  signed [16:0] dataOut;  // sfix17_En12


  reg signed [16:0] delayedSignals0;  // sfix17_En12
  wire signed [16:0] ZEROCONST;  // sfix17_En12
  wire signed [16:0] switchDataOut;  // sfix17_En12
  reg signed [16:0] dataOut_1;  // sfix17_En12


  always @(posedge clk or posedge reset)
    begin : delay0_process
      if (reset == 1'b1) begin
        delayedSignals0 <= 17'sb00000000000000000;
      end
      else begin
        if (enb && validIn) begin
          delayedSignals0 <= dataIn;
        end
      end
    end

  assign delayLineEnd = delayedSignals0;

  assign ZEROCONST = 17'sb00000000000000000;

  assign switchDataOut = (lutaddr == 1'b0 ? delayedSignals0 :
              ZEROCONST);

  always @(posedge clk or posedge reset)
    begin : dataOutReg_process
      if (reset == 1'b1) begin
        dataOut_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          dataOut_1 <= switchDataOut;
        end
      end
    end

  assign dataOut = dataOut_1;

endmodule  // Addressable_Delay_Line_block7

