// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\Addressable_Delay_Line_block9.v
// Created: 2026-01-26 17:23:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Addressable_Delay_Line_block9
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF2/FIRPartlySerial/Addressable_Delay_Line
// Hierarchy Level: 3
// Model version: 17.86
// 
// Addressable Delay Line
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Addressable_Delay_Line_block9
          (clk,
           reset,
           enb,
           dataIn,
           wrEn,
           delayLineEnd);


  input   clk;
  input   reset;
  input   enb;
  input   signed [66:0] dataIn;  // sfix67_En62
  input   wrEn;
  output  signed [66:0] delayLineEnd;  // sfix67_En62


  reg signed [66:0] delayedSignals0;  // sfix67_En62
  reg signed [66:0] delayedSignals1;  // sfix67_En62


  always @(posedge clk or posedge reset)
    begin : delay0_process
      if (reset == 1'b1) begin
        delayedSignals0 <= 67'sh00000000000000000;
      end
      else begin
        if (enb && wrEn) begin
          delayedSignals0 <= dataIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delay1_process
      if (reset == 1'b1) begin
        delayedSignals1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb && wrEn) begin
          delayedSignals1 <= delayedSignals0;
        end
      end
    end

  assign delayLineEnd = delayedSignals1;

endmodule  // Addressable_Delay_Line_block9

