// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\Addressable_Delay_Line.v
// Created: 2026-01-26 17:23:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Addressable_Delay_Line
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/FIRPartlySerial/Addressable_Delay_Line
// Hierarchy Level: 3
// Model version: 17.86
// 
// Addressable Delay Line
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Addressable_Delay_Line
          (clk,
           reset,
           enb,
           dataIn,
           wrEn,
           rdAddr,
           delayLineEnd,
           dataOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [33:0] dataIn;  // sfix34_En30
  input   wrEn;
  input   rdAddr;  // ufix1
  output  signed [33:0] delayLineEnd;  // sfix34_En30
  output  signed [33:0] dataOut;  // sfix34_En30


  reg signed [33:0] delayedSignals0;  // sfix34_En30
  reg signed [33:0] delayedSignals1;  // sfix34_En30
  wire signed [33:0] switchDataOut;  // sfix34_En30
  reg signed [33:0] dataOut_1;  // sfix34_En30


  always @(posedge clk or posedge reset)
    begin : delay0_process
      if (reset == 1'b1) begin
        delayedSignals0 <= 34'sh000000000;
      end
      else begin
        if (enb && wrEn) begin
          delayedSignals0 <= dataIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delay1_process
      if (reset == 1'b1) begin
        delayedSignals1 <= 34'sh000000000;
      end
      else begin
        if (enb && wrEn) begin
          delayedSignals1 <= delayedSignals0;
        end
      end
    end

  assign delayLineEnd = delayedSignals1;

  assign switchDataOut = (rdAddr == 1'b0 ? delayedSignals0 :
              delayedSignals1);

  always @(posedge clk or posedge reset)
    begin : dataOutReg_process
      if (reset == 1'b1) begin
        dataOut_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          dataOut_1 <= switchDataOut;
        end
      end
    end

  assign dataOut = dataOut_1;

endmodule  // Addressable_Delay_Line

