// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\DECIMATOR.v
// Created: 2026-01-30 10:39:16
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-06
// Target subsystem base rate: 1e-06
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-06
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out2                          ce_out        1e-06
// Out1                          ce_out        1e-06
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DECIMATOR
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR
// Hierarchy Level: 0
// Model version: 17.87
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DECIMATOR
          (clk,
           reset,
           clk_enable,
           In1,
           In2,
           ce_out,
           Out2,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [1:0] In1;  // sfix2
  input   In2;
  output  ce_out;
  output  signed [15:0] Out2;  // sfix16_En11
  output  Out1;


  wire signed [15:0] CIC_Decimator_out1;  // sfix16_En14
  wire CIC_Decimator_out2;
  wire signed [15:0] DCF_out1;  // sfix16_En13
  wire DCF_out2;
  wire signed [15:0] HBF1_out1;  // sfix16_En12
  wire HBF1_out2;
  wire signed [15:0] HBF2_out1;  // sfix16_En11
  wire HBF2_out2;


  // StartHere
  CICDecimation u_CIC_Decimator_inst (.clk(clk),
                                      .reset(reset),
                                      .enb(clk_enable),
                                      .dataIn(In1),  // sfix2
                                      .validIn(In2),
                                      .dataOut(CIC_Decimator_out1),  // sfix16_En14
                                      .validOut(CIC_Decimator_out2)
                                      );

  DCF u_DCF (.clk(clk),
             .reset(reset),
             .enb(clk_enable),
             .dataIn(CIC_Decimator_out1),  // sfix16_En14
             .validIn(CIC_Decimator_out2),
             .dataOut(DCF_out1),  // sfix16_En13
             .validOut(DCF_out2)
             );

  HBF1 u_HBF1 (.clk(clk),
               .reset(reset),
               .enb(clk_enable),
               .dataIn(DCF_out1),  // sfix16_En13
               .validIn(DCF_out2),
               .dataOut(HBF1_out1),  // sfix16_En12
               .validOut(HBF1_out2)
               );

  HBF2 u_HBF2 (.clk(clk),
               .reset(reset),
               .enb(clk_enable),
               .dataIn(HBF1_out1),  // sfix16_En12
               .validIn(HBF1_out2),
               .dataOut(HBF2_out1),  // sfix16_En11
               .validOut(HBF2_out2)
               );

  assign Out2 = HBF2_out1;

  assign Out1 = HBF2_out2;

  assign ce_out = clk_enable;

endmodule  // DECIMATOR

