// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\Filter.v
// Created: 2026-01-26 17:23:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/DCF/Filter
// Hierarchy Level: 2
// Model version: 17.86
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En14
  input   validIn;
  input   syncReset;
  output  signed [32:0] dataOut;  // sfix33_En30
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En14
  reg signed [15:0] dinReg2_0_re;  // sfix16_En14
  wire signed [15:0] CoefOut_0;  // sfix16_En16
  wire signed [15:0] CoefOut_1;  // sfix16_En16
  wire signed [15:0] CoefOut_2;  // sfix16_En16
  wire signed [15:0] CoefOut_3;  // sfix16_En16
  wire signed [15:0] CoefOut_4;  // sfix16_En16
  wire signed [15:0] CoefOut_5;  // sfix16_En16
  wire signed [15:0] CoefOut_6;  // sfix16_En16
  reg  dinReg2Vld;
  wire signed [32:0] dout_1_re;  // sfix33_En30
  wire doutVld;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn;
            end
          end
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinReg2_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end

  FilterCoef u_CoefTable_1 (.CoefOut_0(CoefOut_0),  // sfix16_En16
                            .CoefOut_1(CoefOut_1),  // sfix16_En16
                            .CoefOut_2(CoefOut_2),  // sfix16_En16
                            .CoefOut_3(CoefOut_3),  // sfix16_En16
                            .CoefOut_4(CoefOut_4),  // sfix16_En16
                            .CoefOut_5(CoefOut_5),  // sfix16_En16
                            .CoefOut_6(CoefOut_6)  // sfix16_En16
                            );

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end

  subFilter u_subFilter_1_re (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                              .coefIn_0(CoefOut_0),  // sfix16_En16
                              .coefIn_1(CoefOut_1),  // sfix16_En16
                              .coefIn_2(CoefOut_2),  // sfix16_En16
                              .coefIn_3(CoefOut_3),  // sfix16_En16
                              .coefIn_4(CoefOut_4),  // sfix16_En16
                              .coefIn_5(CoefOut_5),  // sfix16_En16
                              .coefIn_6(CoefOut_6),  // sfix16_En16
                              .dinRegVld(dinReg2Vld),
                              .syncReset(syncReset),
                              .dout_1_re(dout_1_re),  // sfix33_En30
                              .doutVld(doutVld)
                              );

  assign dataOut = dout_1_re;

  assign validOut = doutVld;

endmodule  // Filter

