// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\FilterTapSystolicPreAdd_block.v
// Created: 2026-01-26 17:23:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicPreAdd_block
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF2/FIRPartlySerial/FilterTapSystolicPreAdd
// Hierarchy Level: 3
// Model version: 17.86
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicPreAdd_block
          (clk,
           reset,
           enb,
           din_re,
           preAddIn,
           coeff,
           sumIn,
           sumOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [66:0] din_re;  // sfix67_En62
  input   signed [66:0] preAddIn;  // sfix67_En62
  input   signed [66:0] coeff;  // sfix67_En66
  input   signed [132:0] sumIn;  // sfix133_En128
  output  signed [132:0] sumOut;  // sfix133_En128


  reg signed [66:0] fTap_din1_reg1;  // sfix67
  reg signed [66:0] fTap_din1_reg2;  // sfix67
  reg signed [66:0] fTap_din2_reg1;  // sfix67
  reg signed [67:0] fTap_preAdd_reg;  // sfix68
  reg signed [134:0] fTap_mult_reg;  // sfix135
  reg signed [132:0] fTap_addout_reg;  // sfix133
  reg signed [66:0] fTap_coef_reg1;  // sfix67
  reg signed [66:0] fTap_coef_reg2;  // sfix67
  wire signed [67:0] fTap_preAdd_reg_next;  // sfix68_En62
  wire signed [134:0] fTap_mult_reg_next;  // sfix135_En128
  wire signed [132:0] fTap_addout_reg_next;  // sfix133_En128
  wire signed [132:0] fTap_add_cast;  // sfix133_En128
  wire signed [67:0] fTap_add_cast_1;  // sfix68_En62
  wire signed [67:0] fTap_add_cast_2;  // sfix68_En62


  // FilterTapSystolicPreAddS
  always @(posedge clk or posedge reset)
    begin : fTap_process
      if (reset == 1'b1) begin
        fTap_din1_reg1 <= 67'sh00000000000000000;
        fTap_din1_reg2 <= 67'sh00000000000000000;
        fTap_din2_reg1 <= 67'sh00000000000000000;
        fTap_preAdd_reg <= 68'sh00000000000000000;
        fTap_coef_reg1 <= 67'sh00000000000000000;
        fTap_coef_reg2 <= 67'sh00000000000000000;
        fTap_mult_reg <= 135'sh0000000000000000000000000000000000;
        fTap_addout_reg <= 133'sh0000000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          fTap_preAdd_reg <= fTap_preAdd_reg_next;
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
          fTap_din1_reg2 <= fTap_din1_reg1;
          fTap_din1_reg1 <= din_re;
          fTap_din2_reg1 <= preAddIn;
          fTap_coef_reg2 <= fTap_coef_reg1;
          fTap_coef_reg1 <= coeff;
        end
      end
    end

  assign sumOut = fTap_addout_reg;
  assign fTap_add_cast = fTap_mult_reg[132:0];
  assign fTap_addout_reg_next = fTap_add_cast + sumIn;
  assign fTap_mult_reg_next = fTap_preAdd_reg * fTap_coef_reg2;
  assign fTap_add_cast_1 = {fTap_din1_reg2[66], fTap_din1_reg2};
  assign fTap_add_cast_2 = {fTap_din2_reg1[66], fTap_din2_reg1};
  assign fTap_preAdd_reg_next = fTap_add_cast_1 + fTap_add_cast_2;

endmodule  // FilterTapSystolicPreAdd_block

