// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\FilterTapSystolicPreAdd.v
// Created: 2026-01-26 17:23:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicPreAdd
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/FIRPartlySerial/FilterTapSystolicPreAdd
// Hierarchy Level: 3
// Model version: 17.86
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicPreAdd
          (clk,
           reset,
           enb,
           din_re,
           preAddIn,
           coeff,
           sumIn,
           sumOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [33:0] din_re;  // sfix34_En30
  input   signed [33:0] preAddIn;  // sfix34_En30
  input   signed [33:0] coeff;  // sfix34_En33
  input   signed [66:0] sumIn;  // sfix67_En63
  output  signed [66:0] sumOut;  // sfix67_En63


  reg signed [33:0] fTap_din1_reg1;  // sfix34
  reg signed [33:0] fTap_din1_reg2;  // sfix34
  reg signed [33:0] fTap_din2_reg1;  // sfix34
  reg signed [34:0] fTap_preAdd_reg;  // sfix35
  reg signed [68:0] fTap_mult_reg;  // sfix69
  reg signed [66:0] fTap_addout_reg;  // sfix67
  reg signed [33:0] fTap_coef_reg1;  // sfix34
  reg signed [33:0] fTap_coef_reg2;  // sfix34
  wire signed [34:0] fTap_preAdd_reg_next;  // sfix35_En30
  wire signed [68:0] fTap_mult_reg_next;  // sfix69_En63
  wire signed [66:0] fTap_addout_reg_next;  // sfix67_En63
  wire signed [66:0] fTap_add_cast;  // sfix67_En63
  wire signed [34:0] fTap_add_cast_1;  // sfix35_En30
  wire signed [34:0] fTap_add_cast_2;  // sfix35_En30


  // FilterTapSystolicPreAddS
  always @(posedge clk or posedge reset)
    begin : fTap_process
      if (reset == 1'b1) begin
        fTap_din1_reg1 <= 34'sh000000000;
        fTap_din1_reg2 <= 34'sh000000000;
        fTap_din2_reg1 <= 34'sh000000000;
        fTap_preAdd_reg <= 35'sh000000000;
        fTap_coef_reg1 <= 34'sh000000000;
        fTap_coef_reg2 <= 34'sh000000000;
        fTap_mult_reg <= 69'sh000000000000000000;
        fTap_addout_reg <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          fTap_preAdd_reg <= fTap_preAdd_reg_next;
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
          fTap_din1_reg2 <= fTap_din1_reg1;
          fTap_din1_reg1 <= din_re;
          fTap_din2_reg1 <= preAddIn;
          fTap_coef_reg2 <= fTap_coef_reg1;
          fTap_coef_reg1 <= coeff;
        end
      end
    end

  assign sumOut = fTap_addout_reg;
  assign fTap_add_cast = fTap_mult_reg[66:0];
  assign fTap_addout_reg_next = fTap_add_cast + sumIn;
  assign fTap_mult_reg_next = fTap_preAdd_reg * fTap_coef_reg2;
  assign fTap_add_cast_1 = {fTap_din1_reg2[33], fTap_din1_reg2};
  assign fTap_add_cast_2 = {fTap_din2_reg1[33], fTap_din2_reg1};
  assign fTap_preAdd_reg_next = fTap_add_cast_1 + fTap_add_cast_2;

endmodule  // FilterTapSystolicPreAdd

