// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\FilterTapSystolicPreAdd.v
// Created: 2026-01-30 11:58:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicPreAdd
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/FIRPartlySerial/FilterTapSystolicPreAdd
// Hierarchy Level: 3
// Model version: 17.90
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicPreAdd
          (clk,
           reset,
           enb,
           din_re,
           preAddIn,
           coeff,
           sumIn,
           sumOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [16:0] din_re;  // sfix17_En13
  input   signed [16:0] preAddIn;  // sfix17_En13
  input   signed [16:0] coeff;  // sfix17_En16
  input   signed [32:0] sumIn;  // sfix33_En29
  output  signed [32:0] sumOut;  // sfix33_En29


  reg signed [16:0] fTap_din1_reg1;  // sfix17
  reg signed [16:0] fTap_din1_reg2;  // sfix17
  reg signed [16:0] fTap_din2_reg1;  // sfix17
  reg signed [17:0] fTap_preAdd_reg;  // sfix18
  reg signed [34:0] fTap_mult_reg;  // sfix35
  reg signed [32:0] fTap_addout_reg;  // sfix33
  reg signed [16:0] fTap_coef_reg1;  // sfix17
  reg signed [16:0] fTap_coef_reg2;  // sfix17
  wire signed [17:0] fTap_preAdd_reg_next;  // sfix18_En13
  wire signed [34:0] fTap_mult_reg_next;  // sfix35_En29
  wire signed [32:0] fTap_addout_reg_next;  // sfix33_En29
  wire signed [32:0] fTap_add_cast;  // sfix33_En29
  wire signed [17:0] fTap_add_cast_1;  // sfix18_En13
  wire signed [17:0] fTap_add_cast_2;  // sfix18_En13


  // FilterTapSystolicPreAddS
  always @(posedge clk or posedge reset)
    begin : fTap_process
      if (reset == 1'b1) begin
        fTap_din1_reg1 <= 17'sb00000000000000000;
        fTap_din1_reg2 <= 17'sb00000000000000000;
        fTap_din2_reg1 <= 17'sb00000000000000000;
        fTap_preAdd_reg <= 18'sb000000000000000000;
        fTap_coef_reg1 <= 17'sb00000000000000000;
        fTap_coef_reg2 <= 17'sb00000000000000000;
        fTap_mult_reg <= 35'sh000000000;
        fTap_addout_reg <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          fTap_preAdd_reg <= fTap_preAdd_reg_next;
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
          fTap_din1_reg2 <= fTap_din1_reg1;
          fTap_din1_reg1 <= din_re;
          fTap_din2_reg1 <= preAddIn;
          fTap_coef_reg2 <= fTap_coef_reg1;
          fTap_coef_reg1 <= coeff;
        end
      end
    end

  assign sumOut = fTap_addout_reg;
  assign fTap_add_cast = fTap_mult_reg[32:0];
  assign fTap_addout_reg_next = fTap_add_cast + sumIn;
  assign fTap_mult_reg_next = fTap_preAdd_reg * fTap_coef_reg2;
  assign fTap_add_cast_1 = {fTap_din1_reg2[16], fTap_din1_reg2};
  assign fTap_add_cast_2 = {fTap_din2_reg1[16], fTap_din2_reg1};
  assign fTap_preAdd_reg_next = fTap_add_cast_1 + fTap_add_cast_2;

endmodule  // FilterTapSystolicPreAdd

