// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\FIRPartlySerial_block.v
// Created: 2026-01-30 10:39:16
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIRPartlySerial_block
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1/FIRPartlySerial
// Hierarchy Level: 2
// Model version: 17.87
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIRPartlySerial_block
          (clk,
           reset,
           enb,
           filterInput,
           ctrl,
           subfilterOutTmp_2,
           subfilterOutTmp_vld2);


  input   clk;
  input   reset;
  input   enb;
  input   signed [16:0] filterInput;  // sfix17_En13
  input   ctrl;
  output  signed [33:0] subfilterOutTmp_2;  // sfix34_En29
  output  subfilterOutTmp_vld2;


  wire signed [16:0] coeff;  // sfix17_En13
  wire haltProcess;
  wire signed [16:0] dinSM;  // sfix17_En13
  wire dinVldSM;
  reg  nextDelayLineRdAddrReverse;  // ufix1
  reg  rdCountReverse_1;  // ufix1
  reg  nextDelayLineWrAddr;  // ufix1
  reg  wrCount_1;  // ufix1
  reg  nextDelayLineRdAddr;  // ufix1
  reg  rdCount_1;  // ufix1
  reg  nextSharingCount;  // ufix1
  reg  sharingCount_1;  // ufix1
  reg  delayLineValidInP;
  reg  lastPhaseStrobe;
  reg  delayLineShiftEnP;
  reg  delayLineShiftEn1_1;
  reg  delayLineShiftEn2_1;
  reg  delayLineShiftEn3_1;
  reg  delayLineShiftEn4_1;
  reg  [6:0] validOutLookahead_reg;  // ufix1 [7]
  wire validOutLookahead_1;
  reg  vldOut_1;
  wire notValid;
  reg  rdAddr0_1;  // ufix1
  reg  rdAddr1;  // ufix1
  reg  rdAddr2;  // ufix1
  reg  rdAddr3;  // ufix1
  reg  rdAddr4;  // ufix1
  wire rdAddrEndZero;
  reg  [5:0] finalSumValidPipe_reg;  // ufix1 [6]
  wire accumulate;
  wire signed [32:0] accDataOut;  // sfix33_En29
  reg signed [16:0] coeffTableOut3;  // sfix17_En16
  reg signed [16:0] coeffTableRegP3_1;  // sfix17_En16
  reg signed [16:0] coeffTableReg3_1;  // sfix17_En16
  wire coeffNonZero;
  wire signed [33:0] gainOut;  // sfix34_En29
  wire signed [16:0] delayLineEnd0;  // sfix17_En13
  reg signed [16:0] delayLineDataIn1_1;  // sfix17_En13
  wire signed [16:0] delayLineEnd1;  // sfix17_En13
  reg signed [16:0] delayLineDataIn2_1;  // sfix17_En13
  wire signed [16:0] delayLineEnd2;  // sfix17_En13
  reg signed [16:0] delayLineDataIn3_1;  // sfix17_En13
  wire signed [16:0] delayLineDataOut3;  // sfix17_En13
  wire signed [33:0] gainOut_1;  // sfix34_En29
  reg signed [33:0] gainOutDB;  // sfix34_En29
  wire signed [33:0] gainOutSwitch;  // sfix34_En29
  reg signed [33:0] filterDelay_reg [0:3];  // sfix34 [4]
  reg signed [33:0] filterDelay_reg_next [0:3];  // sfix34_En29 [4]
  reg signed [33:0] gainOutREG;  // sfix34_En29
  wire signed [32:0] sumOut_2;  // sfix33_En29
  reg signed [32:0] sumOutReg_1;  // sfix33_En29
  reg signed [32:0] accDataOut_1;  // sfix33_En29
  wire signed [32:0] accSwitchOut;  // sfix33_En29
  wire signed [32:0] accAdderOut;  // sfix33_En29
  wire signed [33:0] converterOut;  // sfix34_En29
  reg signed [33:0] dout_re_1;  // sfix34_En29
  wire signed [33:0] dataZero;  // sfix34_En29
  reg  InputControl_out4_0;  // ufix1
  reg [1:0] InputControl_add_temp;  // ufix2
  reg [1:0] InputControl_add_temp_0;  // ufix2
  reg [1:0] InputControl_sub_temp;  // ufix2
  reg [1:0] InputControl_add_temp_1;  // ufix2
  reg [1:0] InputControl_add_temp_2;  // ufix2
  reg [1:0] InputControl_t_0_0;  // ufix2
  reg [1:0] InputControl_t_1;  // ufix2
  reg [1:0] InputControl_t_2_0;  // ufix2
  reg [1:0] InputControl_t_3;  // ufix2
  reg [1:0] InputControl_t_4;  // ufix2
  reg signed [31:0] filterDelay_t_0_0;  // int32
  reg signed [31:0] filterDelay_t_0_1;  // int32
  reg signed [31:0] filterDelay_t_1;  // int32

  initial begin
    coeffTableRegP3_1 = 17'sb00000000000000000;
  end

  assign coeff = 17'sb00000000000000000;

  assign haltProcess = 1'b0;

  FirRdyLogic_block u_firRdyLogic (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .dinSwitch(filterInput),  // sfix17_En13
                                   .dinVldSwitch(ctrl),
                                   .coeff(coeff),  // sfix17_En13
                                   .haltProcess(haltProcess),
                                   .dinSM(dinSM),  // sfix17_En13
                                   .dinVldSM(dinVldSM)
                                   );

  always @(posedge clk or posedge reset)
    begin : rdCountReverse_process
      if (reset == 1'b1) begin
        rdCountReverse_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdCountReverse_1 <= nextDelayLineRdAddrReverse;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : wrCount_process
      if (reset == 1'b1) begin
        wrCount_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          wrCount_1 <= nextDelayLineWrAddr;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdCount_process
      if (reset == 1'b1) begin
        rdCount_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdCount_1 <= nextDelayLineRdAddr;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : sharingCount_process
      if (reset == 1'b1) begin
        sharingCount_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          sharingCount_1 <= nextSharingCount;
        end
      end
    end

  // Input control counter combinatorial logic
  always @(dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1) begin
    InputControl_add_temp = 2'b00;
    InputControl_add_temp_0 = 2'b00;
    InputControl_sub_temp = 2'b00;
    InputControl_add_temp_1 = 2'b00;
    InputControl_add_temp_2 = 2'b00;
    InputControl_t_0_0 = 2'b00;
    InputControl_t_1 = 2'b00;
    InputControl_t_2_0 = 2'b00;
    InputControl_t_3 = 2'b00;
    InputControl_t_4 = 2'b00;
    delayLineValidInP = (sharingCount_1 == 1'b0) && (dinVldSM == 1'b1);
    lastPhaseStrobe = sharingCount_1 == 1'b1;
    if ((dinVldSM == 1'b1) || (sharingCount_1 > 1'b0)) begin
      if (sharingCount_1 == 1'b1) begin
        nextSharingCount = 1'b0;
      end
      else begin
        InputControl_t_4 = {1'b0, sharingCount_1};
        InputControl_add_temp = InputControl_t_4 + 2'b01;
        nextSharingCount = InputControl_add_temp[0];
      end
    end
    else begin
      nextSharingCount = sharingCount_1;
    end
    if (dinVldSM == 1'b1) begin
      if (wrCount_1 == 1'b1) begin
        InputControl_out4_0 = 1'b0;
      end
      else begin
        InputControl_t_3 = {1'b0, wrCount_1};
        InputControl_add_temp_0 = InputControl_t_3 + 2'b01;
        InputControl_out4_0 = InputControl_add_temp_0[0];
      end
    end
    else begin
      InputControl_out4_0 = wrCount_1;
    end
    if ((rdCount_1 != InputControl_out4_0) || (dinVldSM == 1'b1)) begin
      if (rdCount_1 == 1'b0) begin
        nextDelayLineRdAddr = 1'b1;
      end
      else begin
        InputControl_t_2_0 = {1'b0, rdCount_1};
        InputControl_sub_temp = InputControl_t_2_0 - 2'b01;
        nextDelayLineRdAddr = InputControl_sub_temp[0];
      end
    end
    else begin
      nextDelayLineRdAddr = rdCount_1;
    end
    if ((sharingCount_1 > 1'b0) || (dinVldSM == 1'b1)) begin
      if (sharingCount_1 == 1'b1) begin
        if (wrCount_1 == 1'b1) begin
          nextDelayLineRdAddrReverse = 1'b0;
        end
        else begin
          InputControl_t_0_0 = {1'b0, wrCount_1};
          InputControl_add_temp_2 = InputControl_t_0_0 + 2'b01;
          nextDelayLineRdAddrReverse = InputControl_add_temp_2[0];
        end
      end
      else if (rdCountReverse_1 == 1'b1) begin
        nextDelayLineRdAddrReverse = 1'b0;
      end
      else begin
        InputControl_t_1 = {1'b0, rdCountReverse_1};
        InputControl_add_temp_1 = InputControl_t_1 + 2'b01;
        nextDelayLineRdAddrReverse = InputControl_add_temp_1[0];
      end
    end
    else begin
      nextDelayLineRdAddrReverse = rdCountReverse_1;
    end
    nextDelayLineWrAddr = InputControl_out4_0;
  end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn0_process
      if (reset == 1'b1) begin
        delayLineShiftEnP <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEnP <= lastPhaseStrobe;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn1_process
      if (reset == 1'b1) begin
        delayLineShiftEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn1_1 <= delayLineShiftEnP;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn2_process
      if (reset == 1'b1) begin
        delayLineShiftEn2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn2_1 <= delayLineShiftEn1_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn3_process
      if (reset == 1'b1) begin
        delayLineShiftEn3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn3_1 <= delayLineShiftEn2_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn4_process
      if (reset == 1'b1) begin
        delayLineShiftEn4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn4_1 <= delayLineShiftEn3_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : validOutLookahead_process
      if (reset == 1'b1) begin
        validOutLookahead_reg <= {7{1'b0}};
      end
      else begin
        if (enb) begin
          validOutLookahead_reg[0] <= delayLineShiftEn4_1;
          validOutLookahead_reg[32'sd6:32'sd1] <= validOutLookahead_reg[32'sd5:32'sd0];
        end
      end
    end

  assign validOutLookahead_1 = validOutLookahead_reg[6];

  always @(posedge clk or posedge reset)
    begin : vldOut_process
      if (reset == 1'b1) begin
        vldOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          vldOut_1 <= validOutLookahead_1;
        end
      end
    end

  assign notValid =  ~ vldOut_1;

  always @(posedge clk or posedge reset)
    begin : rdAddr0_process
      if (reset == 1'b1) begin
        rdAddr0_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr0_1 <= sharingCount_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr0_2_process
      if (reset == 1'b1) begin
        rdAddr1 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr1 <= rdAddr0_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr1_1_process
      if (reset == 1'b1) begin
        rdAddr2 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr2 <= rdAddr1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr2_1_process
      if (reset == 1'b1) begin
        rdAddr3 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr3 <= rdAddr2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr3_1_process
      if (reset == 1'b1) begin
        rdAddr4 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr4 <= rdAddr3;
        end
      end
    end

  assign rdAddrEndZero =  ~ rdAddr4;

  always @(posedge clk or posedge reset)
    begin : finalSumValidPipe_process
      if (reset == 1'b1) begin
        finalSumValidPipe_reg <= {6{1'b0}};
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg[0] <= rdAddrEndZero;
          finalSumValidPipe_reg[32'sd5:32'sd1] <= finalSumValidPipe_reg[32'sd4:32'sd0];
        end
      end
    end

  assign accumulate = finalSumValidPipe_reg[5];

  assign accDataOut = 33'sh000000000;

  // Coefficient table for multiplier3
  always @(rdAddr3) begin
    case ( rdAddr3)
      1'b0 :
        begin
          coeffTableOut3 = 17'sb01000000000000000;
        end
      1'b1 :
        begin
          coeffTableOut3 = 17'sb00000000000000000;
        end
      default :
        begin
          coeffTableOut3 = 17'sb00000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP3_process
      if (enb) begin
        coeffTableRegP3_1 <= coeffTableOut3;
      end
    end

  always @(posedge clk or posedge reset)
    begin : coeffTableReg3_process
      if (reset == 1'b1) begin
        coeffTableReg3_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg3_1 <= coeffTableRegP3_1;
        end
      end
    end

  assign coeffNonZero = coeffTableReg3_1 != 17'sb00000000000000000;

  assign gainOut = 34'sh000000000;

  Addressable_Delay_Line_block3 u_delayLine0 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(dinSM),  // sfix17_En13
                                              .wrEn(delayLineValidInP),
                                              .delayLineEnd(delayLineEnd0)  // sfix17_En13
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn1_process
      if (reset == 1'b1) begin
        delayLineDataIn1_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_1 <= delayLineEnd0;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine1 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn1_1),  // sfix17_En13
                                              .wrEn(delayLineShiftEn1_1),
                                              .delayLineEnd(delayLineEnd1)  // sfix17_En13
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn2_process
      if (reset == 1'b1) begin
        delayLineDataIn2_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn2_1 <= delayLineEnd1;
        end
      end
    end

  Addressable_Delay_Line_block3 u_delayLine2 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn2_1),  // sfix17_En13
                                              .wrEn(delayLineShiftEn2_1),
                                              .delayLineEnd(delayLineEnd2)  // sfix17_En13
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn3_process
      if (reset == 1'b1) begin
        delayLineDataIn3_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn3_1 <= delayLineEnd2;
        end
      end
    end

  Addressable_Delay_Line_block4 u_delayLine3 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn3_1),  // sfix17_En13
                                              .validIn(delayLineShiftEn3_1),
                                              .rdAddr(rdAddr3),  // ufix1
                                              .dataOut(delayLineDataOut3)  // sfix17_En13
                                              );

  assign gainOut_1 = {{2{delayLineDataOut3[16]}}, {delayLineDataOut3, 15'b000000000000000}};

  always @(posedge clk or posedge reset)
    begin : filterDelay_process
      if (reset == 1'b1) begin
        gainOutDB <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          gainOutDB <= gainOut_1;
        end
      end
    end

  assign gainOutSwitch = (coeffNonZero == 1'b0 ? gainOut :
              gainOutDB);

  always @(posedge clk or posedge reset)
    begin : filterDelay_1_process
      if (reset == 1'b1) begin
        for(filterDelay_t_1 = 32'sd0; filterDelay_t_1 <= 32'sd3; filterDelay_t_1 = filterDelay_t_1 + 32'sd1) begin
          filterDelay_reg[filterDelay_t_1] <= 34'sh000000000;
        end
      end
      else begin
        if (enb) begin
          for(filterDelay_t_0_1 = 32'sd0; filterDelay_t_0_1 <= 32'sd3; filterDelay_t_0_1 = filterDelay_t_0_1 + 32'sd1) begin
            filterDelay_reg[filterDelay_t_0_1] <= filterDelay_reg_next[filterDelay_t_0_1];
          end
        end
      end
    end

  always @* begin
    gainOutREG = filterDelay_reg[3];
    filterDelay_reg_next[0] = gainOutSwitch;

    for(filterDelay_t_0_0 = 32'sd0; filterDelay_t_0_0 <= 32'sd2; filterDelay_t_0_0 = filterDelay_t_0_0 + 32'sd1) begin
      filterDelay_reg_next[filterDelay_t_0_0 + 32'sd1] = filterDelay_reg[filterDelay_t_0_0];
    end

  end

  assign sumOut_2 = gainOutREG[32:0];

  always @(posedge clk or posedge reset)
    begin : sumOutReg_process
      if (reset == 1'b1) begin
        sumOutReg_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          sumOutReg_1 <= sumOut_2;
        end
      end
    end

  assign accSwitchOut = (accumulate == 1'b0 ? accDataOut_1 :
              accDataOut);

  assign accAdderOut = accSwitchOut + sumOutReg_1;

  always @(posedge clk or posedge reset)
    begin : accDataOut_2_process
      if (reset == 1'b1) begin
        accDataOut_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          accDataOut_1 <= accAdderOut;
        end
      end
    end

  assign converterOut = {accDataOut_1[32], accDataOut_1};

  always @(posedge clk or posedge reset)
    begin : dout_re_process
      if (reset == 1'b1) begin
        dout_re_1 <= 34'sh000000000;
      end
      else begin
        if (enb && validOutLookahead_1) begin
          dout_re_1 <= converterOut;
        end
      end
    end

  assign dataZero = 34'sh000000000;

  assign subfilterOutTmp_2 = (notValid == 1'b0 ? dout_re_1 :
              dataZero);

  assign subfilterOutTmp_vld2 = vldOut_1;

endmodule  // FIRPartlySerial_block

