// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\FIRPartlySerial_block1.v
// Created: 2026-01-26 17:23:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIRPartlySerial_block1
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF2/FIRPartlySerial
// Hierarchy Level: 2
// Model version: 17.86
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIRPartlySerial_block1
          (clk,
           reset,
           enb,
           filterInput,
           ctrl,
           subfilterOutTmp_1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [66:0] filterInput;  // sfix67_En62
  input   ctrl;
  output  signed [133:0] subfilterOutTmp_1;  // sfix134_En128


  wire signed [66:0] coeff;  // sfix67_En62
  wire haltProcess;
  wire signed [66:0] dinSM;  // sfix67_En62
  wire dinVldSM;
  reg  nextDelayLineRdAddrReverse;  // ufix1
  reg  rdCountReverse_1;  // ufix1
  reg  nextDelayLineWrAddr;  // ufix1
  reg  wrCount_1;  // ufix1
  reg  nextDelayLineRdAddr;  // ufix1
  reg  rdCount_1;  // ufix1
  reg  nextSharingCount;  // ufix1
  reg  sharingCount_1;  // ufix1
  reg  delayLineValidInP;
  reg  lastPhaseStrobe;
  reg  delayLineShiftEnP;
  reg  delayLineShiftEn1_1;
  reg  delayLineShiftEn2_1;
  reg  delayLineShiftEn3_1;
  reg  delayLineShiftEn4_1;
  reg  delayLineShiftEn5_1;
  reg  delayLineShiftEn6_1;
  reg  delayLineShiftEn7_1;
  reg  [6:0] validOutLookahead_reg;  // ufix1 [7]
  wire validOutLookahead_1;
  reg  vldOut_1;
  wire notValid;
  reg  rdAddr0_1;  // ufix1
  reg  rdAddr1;  // ufix1
  reg  rdAddr2;  // ufix1
  reg  rdAddr3;  // ufix1
  reg  rdAddr4;  // ufix1
  reg  rdAddr5;  // ufix1
  reg  rdAddr6;  // ufix1
  reg  rdAddr7;  // ufix1
  wire rdAddrEndZero;
  reg  [5:0] finalSumValidPipe_reg;  // ufix1 [6]
  wire accumulate;
  wire signed [132:0] accDataOut;  // sfix133_En128
  wire signed [66:0] delayLineEnd0;  // sfix67_En62
  wire signed [66:0] delayLineDataOut0;  // sfix67_En62
  reg signed [66:0] delayLineDataIn1_1;  // sfix67_En62
  wire signed [66:0] delayLineEnd1;  // sfix67_En62
  wire signed [66:0] delayLineDataOut1;  // sfix67_En62
  reg signed [66:0] delayLineDataIn2_1;  // sfix67_En62
  wire signed [66:0] delayLineEnd2;  // sfix67_En62
  wire signed [66:0] delayLineDataOut2;  // sfix67_En62
  reg signed [66:0] delayLineDataIn3_1;  // sfix67_En62
  wire signed [66:0] delayLineEnd3;  // sfix67_En62
  wire signed [66:0] delayLineDataOut3;  // sfix67_En62
  reg signed [66:0] delayLineDataIn4_1;  // sfix67_En62
  wire signed [66:0] delayLineEnd4;  // sfix67_En62
  wire signed [66:0] delayLineDataOut4;  // sfix67_En62
  reg signed [66:0] delayLineDataIn5_1;  // sfix67_En62
  wire signed [66:0] delayLineEnd5;  // sfix67_En62
  wire signed [66:0] delayLineDataOut5;  // sfix67_En62
  reg signed [66:0] delayLineDataIn6_1;  // sfix67_En62
  wire signed [66:0] delayLineEnd6;  // sfix67_En62
  wire signed [66:0] delayLineDataOut6;  // sfix67_En62
  reg signed [66:0] delayLineDataIn7_1;  // sfix67_En62
  wire signed [66:0] delayLineEnd7;  // sfix67_En62
  wire signed [66:0] delayLineDataOut7;  // sfix67_En62
  reg signed [66:0] coeffTableOut6;  // sfix67_En66
  reg signed [66:0] coeffTableRegP6_1;  // sfix67_En66
  reg signed [66:0] coeffTableReg6_1;  // sfix67_En66
  wire signed [66:0] delayLineEnd8;  // sfix67_En62
  wire signed [66:0] delayLineDataOut8;  // sfix67_En62
  reg signed [66:0] coeffTableOut5;  // sfix67_En66
  reg signed [66:0] coeffTableRegP5_1;  // sfix67_En66
  reg signed [66:0] coeffTableReg5_1;  // sfix67_En66
  wire signed [66:0] delayLineEnd9;  // sfix67_En62
  wire signed [66:0] delayLineDataOut9;  // sfix67_En62
  reg signed [66:0] coeffTableOut4;  // sfix67_En66
  reg signed [66:0] coeffTableRegP4_1;  // sfix67_En66
  reg signed [66:0] coeffTableReg4_1;  // sfix67_En66
  wire signed [66:0] delayLineEnd10;  // sfix67_En62
  wire signed [66:0] delayLineDataOut10;  // sfix67_En62
  reg signed [66:0] coeffTableOut3;  // sfix67_En66
  reg signed [66:0] coeffTableRegP3_1;  // sfix67_En66
  reg signed [66:0] coeffTableReg3_1;  // sfix67_En66
  wire signed [66:0] delayLineEnd11;  // sfix67_En62
  wire signed [66:0] delayLineDataOut11;  // sfix67_En62
  reg signed [66:0] coeffTableOut2;  // sfix67_En66
  reg signed [66:0] coeffTableRegP2_1;  // sfix67_En66
  reg signed [66:0] coeffTableReg2_1;  // sfix67_En66
  wire signed [66:0] delayLineEnd12;  // sfix67_En62
  wire signed [66:0] delayLineDataOut12;  // sfix67_En62
  reg signed [66:0] coeffTableOut1;  // sfix67_En66
  reg signed [66:0] coeffTableRegP1_1;  // sfix67_En66
  reg signed [66:0] coeffTableReg1_1;  // sfix67_En66
  wire signed [66:0] delayLineEnd13deadOut;  // sfix67_En62
  wire signed [66:0] delayLineDataOut13;  // sfix67_En62
  reg signed [66:0] coeffTableOut0;  // sfix67_En66
  reg signed [66:0] coeffTableRegP0_1;  // sfix67_En66
  reg signed [66:0] coeffTableReg0_1;  // sfix67_En66
  wire signed [132:0] sumIn;  // sfix133_En128
  wire signed [132:0] sumOut;  // sfix133_En128
  wire signed [132:0] sumOut_0;  // sfix133_En128
  wire signed [132:0] sumOut_1;  // sfix133_En128
  wire signed [132:0] sumOut_2;  // sfix133_En128
  wire signed [132:0] sumOut_3;  // sfix133_En128
  wire signed [132:0] sumOut_4;  // sfix133_En128
  wire signed [132:0] sumOut_5;  // sfix133_En128
  reg signed [132:0] sumOutReg_1;  // sfix133_En128
  reg signed [132:0] accDataOut_1;  // sfix133_En128
  wire signed [132:0] accSwitchOut;  // sfix133_En128
  wire signed [132:0] accAdderOut;  // sfix133_En128
  wire signed [133:0] converterOut;  // sfix134_En128
  reg signed [133:0] dout_re_1;  // sfix134_En128
  wire signed [133:0] dataZero;  // sfix134_En128
  reg  InputControl_out4_0;  // ufix1
  reg [1:0] InputControl_add_temp;  // ufix2
  reg [1:0] InputControl_add_temp_0;  // ufix2
  reg [1:0] InputControl_sub_temp;  // ufix2
  reg [1:0] InputControl_add_temp_1;  // ufix2
  reg [1:0] InputControl_add_temp_2;  // ufix2
  reg [1:0] InputControl_t_0_0;  // ufix2
  reg [1:0] InputControl_t_1;  // ufix2
  reg [1:0] InputControl_t_2_0;  // ufix2
  reg [1:0] InputControl_t_3;  // ufix2
  reg [1:0] InputControl_t_4;  // ufix2

  initial begin
    coeffTableRegP6_1 = 67'sh00000000000000000;
    coeffTableRegP5_1 = 67'sh00000000000000000;
    coeffTableRegP4_1 = 67'sh00000000000000000;
    coeffTableRegP3_1 = 67'sh00000000000000000;
    coeffTableRegP2_1 = 67'sh00000000000000000;
    coeffTableRegP1_1 = 67'sh00000000000000000;
    coeffTableRegP0_1 = 67'sh00000000000000000;
  end

  assign coeff = 67'sh00000000000000000;

  assign haltProcess = 1'b0;

  FirRdyLogic_block1 u_firRdyLogic (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .dinSwitch(filterInput),  // sfix67_En62
                                    .dinVldSwitch(ctrl),
                                    .coeff(coeff),  // sfix67_En62
                                    .haltProcess(haltProcess),
                                    .dinSM(dinSM),  // sfix67_En62
                                    .dinVldSM(dinVldSM)
                                    );

  always @(posedge clk or posedge reset)
    begin : rdCountReverse_process
      if (reset == 1'b1) begin
        rdCountReverse_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdCountReverse_1 <= nextDelayLineRdAddrReverse;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : wrCount_process
      if (reset == 1'b1) begin
        wrCount_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          wrCount_1 <= nextDelayLineWrAddr;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdCount_process
      if (reset == 1'b1) begin
        rdCount_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdCount_1 <= nextDelayLineRdAddr;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : sharingCount_process
      if (reset == 1'b1) begin
        sharingCount_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          sharingCount_1 <= nextSharingCount;
        end
      end
    end

  // Input control counter combinatorial logic
  always @(dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1) begin
    InputControl_add_temp = 2'b00;
    InputControl_add_temp_0 = 2'b00;
    InputControl_sub_temp = 2'b00;
    InputControl_add_temp_1 = 2'b00;
    InputControl_add_temp_2 = 2'b00;
    InputControl_t_0_0 = 2'b00;
    InputControl_t_1 = 2'b00;
    InputControl_t_2_0 = 2'b00;
    InputControl_t_3 = 2'b00;
    InputControl_t_4 = 2'b00;
    delayLineValidInP = (sharingCount_1 == 1'b0) && (dinVldSM == 1'b1);
    lastPhaseStrobe = sharingCount_1 == 1'b1;
    if ((dinVldSM == 1'b1) || (sharingCount_1 > 1'b0)) begin
      if (sharingCount_1 == 1'b1) begin
        nextSharingCount = 1'b0;
      end
      else begin
        InputControl_t_4 = {1'b0, sharingCount_1};
        InputControl_add_temp = InputControl_t_4 + 2'b01;
        nextSharingCount = InputControl_add_temp[0];
      end
    end
    else begin
      nextSharingCount = sharingCount_1;
    end
    if (dinVldSM == 1'b1) begin
      if (wrCount_1 == 1'b1) begin
        InputControl_out4_0 = 1'b0;
      end
      else begin
        InputControl_t_3 = {1'b0, wrCount_1};
        InputControl_add_temp_0 = InputControl_t_3 + 2'b01;
        InputControl_out4_0 = InputControl_add_temp_0[0];
      end
    end
    else begin
      InputControl_out4_0 = wrCount_1;
    end
    if ((rdCount_1 != InputControl_out4_0) || (dinVldSM == 1'b1)) begin
      if (rdCount_1 == 1'b0) begin
        nextDelayLineRdAddr = 1'b1;
      end
      else begin
        InputControl_t_2_0 = {1'b0, rdCount_1};
        InputControl_sub_temp = InputControl_t_2_0 - 2'b01;
        nextDelayLineRdAddr = InputControl_sub_temp[0];
      end
    end
    else begin
      nextDelayLineRdAddr = rdCount_1;
    end
    if ((sharingCount_1 > 1'b0) || (dinVldSM == 1'b1)) begin
      if (sharingCount_1 == 1'b1) begin
        if (wrCount_1 == 1'b1) begin
          nextDelayLineRdAddrReverse = 1'b0;
        end
        else begin
          InputControl_t_0_0 = {1'b0, wrCount_1};
          InputControl_add_temp_2 = InputControl_t_0_0 + 2'b01;
          nextDelayLineRdAddrReverse = InputControl_add_temp_2[0];
        end
      end
      else if (rdCountReverse_1 == 1'b1) begin
        nextDelayLineRdAddrReverse = 1'b0;
      end
      else begin
        InputControl_t_1 = {1'b0, rdCountReverse_1};
        InputControl_add_temp_1 = InputControl_t_1 + 2'b01;
        nextDelayLineRdAddrReverse = InputControl_add_temp_1[0];
      end
    end
    else begin
      nextDelayLineRdAddrReverse = rdCountReverse_1;
    end
    nextDelayLineWrAddr = InputControl_out4_0;
  end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn0_process
      if (reset == 1'b1) begin
        delayLineShiftEnP <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEnP <= lastPhaseStrobe;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn1_process
      if (reset == 1'b1) begin
        delayLineShiftEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn1_1 <= delayLineShiftEnP;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn2_process
      if (reset == 1'b1) begin
        delayLineShiftEn2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn2_1 <= delayLineShiftEn1_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn3_process
      if (reset == 1'b1) begin
        delayLineShiftEn3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn3_1 <= delayLineShiftEn2_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn4_process
      if (reset == 1'b1) begin
        delayLineShiftEn4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn4_1 <= delayLineShiftEn3_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn5_process
      if (reset == 1'b1) begin
        delayLineShiftEn5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn5_1 <= delayLineShiftEn4_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn6_process
      if (reset == 1'b1) begin
        delayLineShiftEn6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn6_1 <= delayLineShiftEn5_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn7_process
      if (reset == 1'b1) begin
        delayLineShiftEn7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn7_1 <= delayLineShiftEn6_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : validOutLookahead_process
      if (reset == 1'b1) begin
        validOutLookahead_reg <= {7{1'b0}};
      end
      else begin
        if (enb) begin
          validOutLookahead_reg[0] <= delayLineShiftEn7_1;
          validOutLookahead_reg[32'sd6:32'sd1] <= validOutLookahead_reg[32'sd5:32'sd0];
        end
      end
    end

  assign validOutLookahead_1 = validOutLookahead_reg[6];

  always @(posedge clk or posedge reset)
    begin : vldOut_process
      if (reset == 1'b1) begin
        vldOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          vldOut_1 <= validOutLookahead_1;
        end
      end
    end

  assign notValid =  ~ vldOut_1;

  always @(posedge clk or posedge reset)
    begin : rdAddr0_process
      if (reset == 1'b1) begin
        rdAddr0_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr0_1 <= sharingCount_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr0_2_process
      if (reset == 1'b1) begin
        rdAddr1 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr1 <= rdAddr0_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr1_1_process
      if (reset == 1'b1) begin
        rdAddr2 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr2 <= rdAddr1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr2_1_process
      if (reset == 1'b1) begin
        rdAddr3 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr3 <= rdAddr2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr3_1_process
      if (reset == 1'b1) begin
        rdAddr4 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr4 <= rdAddr3;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr4_1_process
      if (reset == 1'b1) begin
        rdAddr5 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr5 <= rdAddr4;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr5_1_process
      if (reset == 1'b1) begin
        rdAddr6 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr6 <= rdAddr5;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : rdAddr6_1_process
      if (reset == 1'b1) begin
        rdAddr7 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdAddr7 <= rdAddr6;
        end
      end
    end

  assign rdAddrEndZero =  ~ rdAddr7;

  always @(posedge clk or posedge reset)
    begin : finalSumValidPipe_process
      if (reset == 1'b1) begin
        finalSumValidPipe_reg <= {6{1'b0}};
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg[0] <= rdAddrEndZero;
          finalSumValidPipe_reg[32'sd5:32'sd1] <= finalSumValidPipe_reg[32'sd4:32'sd0];
        end
      end
    end

  assign accumulate = finalSumValidPipe_reg[5];

  assign accDataOut = 133'sh0000000000000000000000000000000000;

  Addressable_Delay_Line_block5 u_delayLine0 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(dinSM),  // sfix67_En62
                                              .wrEn(delayLineValidInP),
                                              .rdAddr(rdAddr0_1),  // ufix1
                                              .delayLineEnd(delayLineEnd0),  // sfix67_En62
                                              .dataOut(delayLineDataOut0)  // sfix67_En62
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn1_process
      if (reset == 1'b1) begin
        delayLineDataIn1_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_1 <= delayLineEnd0;
        end
      end
    end

  Addressable_Delay_Line_block5 u_delayLine1 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn1_1),  // sfix67_En62
                                              .wrEn(delayLineShiftEn1_1),
                                              .rdAddr(rdAddr1),  // ufix1
                                              .delayLineEnd(delayLineEnd1),  // sfix67_En62
                                              .dataOut(delayLineDataOut1)  // sfix67_En62
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn2_process
      if (reset == 1'b1) begin
        delayLineDataIn2_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn2_1 <= delayLineEnd1;
        end
      end
    end

  Addressable_Delay_Line_block5 u_delayLine2 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn2_1),  // sfix67_En62
                                              .wrEn(delayLineShiftEn2_1),
                                              .rdAddr(rdAddr2),  // ufix1
                                              .delayLineEnd(delayLineEnd2),  // sfix67_En62
                                              .dataOut(delayLineDataOut2)  // sfix67_En62
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn3_process
      if (reset == 1'b1) begin
        delayLineDataIn3_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn3_1 <= delayLineEnd2;
        end
      end
    end

  Addressable_Delay_Line_block5 u_delayLine3 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn3_1),  // sfix67_En62
                                              .wrEn(delayLineShiftEn3_1),
                                              .rdAddr(rdAddr3),  // ufix1
                                              .delayLineEnd(delayLineEnd3),  // sfix67_En62
                                              .dataOut(delayLineDataOut3)  // sfix67_En62
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn4_process
      if (reset == 1'b1) begin
        delayLineDataIn4_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn4_1 <= delayLineEnd3;
        end
      end
    end

  Addressable_Delay_Line_block5 u_delayLine4 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn4_1),  // sfix67_En62
                                              .wrEn(delayLineShiftEn4_1),
                                              .rdAddr(rdAddr4),  // ufix1
                                              .delayLineEnd(delayLineEnd4),  // sfix67_En62
                                              .dataOut(delayLineDataOut4)  // sfix67_En62
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn5_process
      if (reset == 1'b1) begin
        delayLineDataIn5_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn5_1 <= delayLineEnd4;
        end
      end
    end

  Addressable_Delay_Line_block5 u_delayLine5 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn5_1),  // sfix67_En62
                                              .wrEn(delayLineShiftEn5_1),
                                              .rdAddr(rdAddr5),  // ufix1
                                              .delayLineEnd(delayLineEnd5),  // sfix67_En62
                                              .dataOut(delayLineDataOut5)  // sfix67_En62
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn6_process
      if (reset == 1'b1) begin
        delayLineDataIn6_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn6_1 <= delayLineEnd5;
        end
      end
    end

  Addressable_Delay_Line_block6 u_delayLine6 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn6_1),  // sfix67_En62
                                              .wrEn(delayLineShiftEn6_1),
                                              .rdAddr(rdAddr6),  // ufix1
                                              .delayLineEnd(delayLineEnd6),  // sfix67_En62
                                              .dataOut(delayLineDataOut6)  // sfix67_En62
                                              );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn7_process
      if (reset == 1'b1) begin
        delayLineDataIn7_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn7_1 <= delayLineEnd6;
        end
      end
    end

  Addressable_Delay_Line_block7 u_delayLine7 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineDataIn7_1),  // sfix67_En62
                                              .validIn(delayLineShiftEn7_1),
                                              .lutaddr(rdAddr7),  // ufix1
                                              .delayLineEnd(delayLineEnd7),  // sfix67_En62
                                              .dataOut(delayLineDataOut7)  // sfix67_En62
                                              );

  // Coefficient table for multiplier6
  always @(rdAddr6) begin
    case ( rdAddr6)
      1'b0 :
        begin
          coeffTableOut6 = 67'sh1419EBA59ADA0B000;
        end
      1'b1 :
        begin
          coeffTableOut6 = 67'sh00000000000000000;
        end
      default :
        begin
          coeffTableOut6 = 67'sh00000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP6_process
      if (enb) begin
        coeffTableRegP6_1 <= coeffTableOut6;
      end
    end

  always @(posedge clk or posedge reset)
    begin : coeffTableReg6_process
      if (reset == 1'b1) begin
        coeffTableReg6_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg6_1 <= coeffTableRegP6_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine8 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineEnd7),  // sfix67_En62
                                              .validIn(delayLineShiftEn6_1),
                                              .rdAddr(rdAddr6),  // ufix1
                                              .delayLineEnd(delayLineEnd8),  // sfix67_En62
                                              .dataOut(delayLineDataOut8)  // sfix67_En62
                                              );

  // Coefficient table for multiplier5
  always @(rdAddr5) begin
    case ( rdAddr5)
      1'b0 :
        begin
          coeffTableOut5 = 67'sh02E8CDAFDC48F6E00;
        end
      1'b1 :
        begin
          coeffTableOut5 = 67'sh79FB294ADECF57C00;
        end
      default :
        begin
          coeffTableOut5 = 67'sh00000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP5_process
      if (enb) begin
        coeffTableRegP5_1 <= coeffTableOut5;
      end
    end

  always @(posedge clk or posedge reset)
    begin : coeffTableReg5_process
      if (reset == 1'b1) begin
        coeffTableReg5_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg5_1 <= coeffTableRegP5_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine9 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dataIn(delayLineEnd8),  // sfix67_En62
                                              .validIn(delayLineShiftEn5_1),
                                              .rdAddr(rdAddr5),  // ufix1
                                              .delayLineEnd(delayLineEnd9),  // sfix67_En62
                                              .dataOut(delayLineDataOut9)  // sfix67_En62
                                              );

  // Coefficient table for multiplier4
  always @(rdAddr4) begin
    case ( rdAddr4)
      1'b0 :
        begin
          coeffTableOut4 = 67'sh00BEC530B5B3C8080;
        end
      1'b1 :
        begin
          coeffTableOut4 = 67'sh7E80E5F50367B4400;
        end
      default :
        begin
          coeffTableOut4 = 67'sh00000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP4_process
      if (enb) begin
        coeffTableRegP4_1 <= coeffTableOut4;
      end
    end

  always @(posedge clk or posedge reset)
    begin : coeffTableReg4_process
      if (reset == 1'b1) begin
        coeffTableReg4_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg4_1 <= coeffTableRegP4_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine10 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineEnd9),  // sfix67_En62
                                               .validIn(delayLineShiftEn4_1),
                                               .rdAddr(rdAddr4),  // ufix1
                                               .delayLineEnd(delayLineEnd10),  // sfix67_En62
                                               .dataOut(delayLineDataOut10)  // sfix67_En62
                                               );

  // Coefficient table for multiplier3
  always @(rdAddr3) begin
    case ( rdAddr3)
      1'b0 :
        begin
          coeffTableOut3 = 67'sh0024BE6BF6D815C40;
        end
      1'b1 :
        begin
          coeffTableOut3 = 67'sh7FA7D988A33527240;
        end
      default :
        begin
          coeffTableOut3 = 67'sh00000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP3_process
      if (enb) begin
        coeffTableRegP3_1 <= coeffTableOut3;
      end
    end

  always @(posedge clk or posedge reset)
    begin : coeffTableReg3_process
      if (reset == 1'b1) begin
        coeffTableReg3_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg3_1 <= coeffTableRegP3_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine11 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineEnd10),  // sfix67_En62
                                               .validIn(delayLineShiftEn3_1),
                                               .rdAddr(rdAddr3),  // ufix1
                                               .delayLineEnd(delayLineEnd11),  // sfix67_En62
                                               .dataOut(delayLineDataOut11)  // sfix67_En62
                                               );

  // Coefficient table for multiplier2
  always @(rdAddr2) begin
    case ( rdAddr2)
      1'b0 :
        begin
          coeffTableOut2 = 67'sh000436C5B90E823A4;
        end
      1'b1 :
        begin
          coeffTableOut2 = 67'sh7FF2889B4889B8240;
        end
      default :
        begin
          coeffTableOut2 = 67'sh00000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP2_process
      if (enb) begin
        coeffTableRegP2_1 <= coeffTableOut2;
      end
    end

  always @(posedge clk or posedge reset)
    begin : coeffTableReg2_process
      if (reset == 1'b1) begin
        coeffTableReg2_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg2_1 <= coeffTableRegP2_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine12 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineEnd11),  // sfix67_En62
                                               .validIn(delayLineShiftEn2_1),
                                               .rdAddr(rdAddr2),  // ufix1
                                               .delayLineEnd(delayLineEnd12),  // sfix67_En62
                                               .dataOut(delayLineDataOut12)  // sfix67_En62
                                               );

  // Coefficient table for multiplier1
  always @(rdAddr1) begin
    case ( rdAddr1)
      1'b0 :
        begin
          coeffTableOut1 = 67'sh000036EC61B08E12C;
        end
      1'b1 :
        begin
          coeffTableOut1 = 67'sh7FFEEAF0FAF4D84BC;
        end
      default :
        begin
          coeffTableOut1 = 67'sh00000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP1_process
      if (enb) begin
        coeffTableRegP1_1 <= coeffTableOut1;
      end
    end

  always @(posedge clk or posedge reset)
    begin : coeffTableReg1_process
      if (reset == 1'b1) begin
        coeffTableReg1_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg1_1 <= coeffTableRegP1_1;
        end
      end
    end

  Addressable_Delay_Line_block8 u_delayLine13 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineEnd12),  // sfix67_En62
                                               .validIn(delayLineShiftEn1_1),
                                               .rdAddr(rdAddr1),  // ufix1
                                               .delayLineEnd(delayLineEnd13deadOut),  // sfix67_En62
                                               .dataOut(delayLineDataOut13)  // sfix67_En62
                                               );

  // Coefficient table for multiplier0
  always @(rdAddr0_1) begin
    case ( rdAddr0_1)
      1'b0 :
        begin
          coeffTableOut0 = 67'sh0000008892D3C7D09;
        end
      1'b1 :
        begin
          coeffTableOut0 = 67'sh7FFFF87E4603C24BE;
        end
      default :
        begin
          coeffTableOut0 = 67'sh00000000000000000;
        end
    endcase
  end

  always @(posedge clk)
    begin : coeffTableRegP0_process
      if (enb) begin
        coeffTableRegP0_1 <= coeffTableOut0;
      end
    end

  always @(posedge clk or posedge reset)
    begin : coeffTableReg0_process
      if (reset == 1'b1) begin
        coeffTableReg0_1 <= 67'sh00000000000000000;
      end
      else begin
        if (enb) begin
          coeffTableReg0_1 <= coeffTableRegP0_1;
        end
      end
    end

  assign sumIn = 133'sh0000000000000000000000000000000000;

  FilterTapSystolicPreAdd_block u_filterTap0 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .din_re(delayLineDataOut0),  // sfix67_En62
                                              .preAddIn(delayLineDataOut13),  // sfix67_En62
                                              .coeff(coeffTableReg0_1),  // sfix67_En66
                                              .sumIn(sumIn),  // sfix133_En128
                                              .sumOut(sumOut)  // sfix133_En128
                                              );

  FilterTapSystolicPreAdd_block u_filterTap1 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .din_re(delayLineDataOut1),  // sfix67_En62
                                              .preAddIn(delayLineDataOut12),  // sfix67_En62
                                              .coeff(coeffTableReg1_1),  // sfix67_En66
                                              .sumIn(sumOut),  // sfix133_En128
                                              .sumOut(sumOut_0)  // sfix133_En128
                                              );

  FilterTapSystolicPreAdd_block u_filterTap2 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .din_re(delayLineDataOut2),  // sfix67_En62
                                              .preAddIn(delayLineDataOut11),  // sfix67_En62
                                              .coeff(coeffTableReg2_1),  // sfix67_En66
                                              .sumIn(sumOut_0),  // sfix133_En128
                                              .sumOut(sumOut_1)  // sfix133_En128
                                              );

  FilterTapSystolicPreAdd_block u_filterTap3 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .din_re(delayLineDataOut3),  // sfix67_En62
                                              .preAddIn(delayLineDataOut10),  // sfix67_En62
                                              .coeff(coeffTableReg3_1),  // sfix67_En66
                                              .sumIn(sumOut_1),  // sfix133_En128
                                              .sumOut(sumOut_2)  // sfix133_En128
                                              );

  FilterTapSystolicPreAdd_block u_filterTap4 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .din_re(delayLineDataOut4),  // sfix67_En62
                                              .preAddIn(delayLineDataOut9),  // sfix67_En62
                                              .coeff(coeffTableReg4_1),  // sfix67_En66
                                              .sumIn(sumOut_2),  // sfix133_En128
                                              .sumOut(sumOut_3)  // sfix133_En128
                                              );

  FilterTapSystolicPreAdd_block u_filterTap5 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .din_re(delayLineDataOut5),  // sfix67_En62
                                              .preAddIn(delayLineDataOut8),  // sfix67_En62
                                              .coeff(coeffTableReg5_1),  // sfix67_En66
                                              .sumIn(sumOut_3),  // sfix133_En128
                                              .sumOut(sumOut_4)  // sfix133_En128
                                              );

  FilterTapSystolicPreAdd_block u_filterTap6 (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .din_re(delayLineDataOut6),  // sfix67_En62
                                              .preAddIn(delayLineDataOut7),  // sfix67_En62
                                              .coeff(coeffTableReg6_1),  // sfix67_En66
                                              .sumIn(sumOut_4),  // sfix133_En128
                                              .sumOut(sumOut_5)  // sfix133_En128
                                              );

  always @(posedge clk or posedge reset)
    begin : sumOutReg_process
      if (reset == 1'b1) begin
        sumOutReg_1 <= 133'sh0000000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          sumOutReg_1 <= sumOut_5;
        end
      end
    end

  assign accSwitchOut = (accumulate == 1'b0 ? accDataOut_1 :
              accDataOut);

  assign accAdderOut = accSwitchOut + sumOutReg_1;

  always @(posedge clk or posedge reset)
    begin : accDataOut_2_process
      if (reset == 1'b1) begin
        accDataOut_1 <= 133'sh0000000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          accDataOut_1 <= accAdderOut;
        end
      end
    end

  assign converterOut = {accDataOut_1[132], accDataOut_1};

  always @(posedge clk or posedge reset)
    begin : dout_re_process
      if (reset == 1'b1) begin
        dout_re_1 <= 134'sh0000000000000000000000000000000000;
      end
      else begin
        if (enb && validOutLookahead_1) begin
          dout_re_1 <= converterOut;
        end
      end
    end

  assign dataZero = 134'sh0000000000000000000000000000000000;

  assign subfilterOutTmp_1 = (notValid == 1'b0 ? dout_re_1 :
              dataZero);

endmodule  // FIRPartlySerial_block1

