// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\HBF1.v
// Created: 2026-01-26 17:23:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HBF1
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF1
// Hierarchy Level: 1
// Model version: 17.86
// 
// HDL FIR Decimation
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HBF1
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [32:0] dataIn;  // sfix33_En30
  input   validIn;
  output  signed [65:0] dataOut;  // sfix66_En62
  output  validOut;


  wire syncReset;
  wire ctrl;
  wire ready;
  wire vldAndRdy;
  wire signed [33:0] dataIn_cast;  // sfix34_En30
  reg signed [33:0] delayLine;  // sfix34_En30
  wire signed [67:0] subfilterOutTmp_1;  // sfix68_En63
  wire vldAndRdy_1;
  reg signed [33:0] delayLine_1;  // sfix34_En30
  wire signed [67:0] subfilterOutTmp_2;  // sfix68_En63
  wire subfilterOutTmp_vld2;
  wire signed [65:0] accOut;  // sfix66_En62
  wire accOutVld;
  wire signed [65:0] ZERO_OUT;  // sfix66_En62
  wire signed [65:0] muxOut;  // sfix66_En62
  reg signed [65:0] dataOut_1;  // sfix66_En62
  reg  validOut_1;


  assign syncReset = 1'b0;

  partlySerialCtrl u_partlySerialCtrl (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .validIn(validIn),
                                       .ctrl(ctrl),
                                       .ready(ready)
                                       );

  assign vldAndRdy = validIn & ready;

  assign dataIn_cast = {dataIn[32], dataIn};

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        delayLine <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            delayLine <= 34'sh000000000;
          end
          else begin
            if (vldAndRdy) begin
              delayLine <= dataIn_cast;
            end
          end
        end
      end
    end

  FIRPartlySerial u_FIRDecim_phase_1 (.clk(clk),
                                      .reset(reset),
                                      .enb(enb),
                                      .filterInput(delayLine),  // sfix34_En30
                                      .ctrl(ctrl),
                                      .subfilterOutTmp_1(subfilterOutTmp_1)  // sfix68_En63
                                      );

  assign vldAndRdy_1 = validIn & ready;

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        delayLine_1 <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            delayLine_1 <= 34'sh000000000;
          end
          else begin
            if (vldAndRdy_1) begin
              delayLine_1 <= delayLine;
            end
          end
        end
      end
    end

  FIRPartlySerial_block u_FIRDecim_phase_2 (.clk(clk),
                                            .reset(reset),
                                            .enb(enb),
                                            .filterInput(delayLine_1),  // sfix34_En30
                                            .ctrl(ctrl),
                                            .subfilterOutTmp_2(subfilterOutTmp_2),  // sfix68_En63
                                            .subfilterOutTmp_vld2(subfilterOutTmp_vld2)
                                            );

  sumTree_firdecim u_FirDecimAccum_2 (.clk(clk),
                                      .reset(reset),
                                      .enb(enb),
                                      .accIn_0(subfilterOutTmp_1),  // sfix68_En63
                                      .accIn_1(subfilterOutTmp_2),  // sfix68_En63
                                      .subfilterOut_vld2(subfilterOutTmp_vld2),
                                      .accOut(accOut),  // sfix66_En62
                                      .accOutVld(accOutVld)
                                      );

  assign ZERO_OUT = 66'sh00000000000000000;

  assign muxOut = (accOutVld == 1'b0 ? ZERO_OUT :
              accOut);

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dataOut_1 <= 66'sh00000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dataOut_1 <= 66'sh00000000000000000;
          end
          else begin
            dataOut_1 <= muxOut;
          end
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        validOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            validOut_1 <= 1'b0;
          end
          else begin
            validOut_1 <= accOutVld;
          end
        end
      end
    end

  assign dataOut = dataOut_1;

  assign validOut = validOut_1;

endmodule  // HBF1

