// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\HBF2.v
// Created: 2026-01-30 10:39:16
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HBF2
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF2
// Hierarchy Level: 1
// Model version: 17.87
// 
// HDL FIR Decimation
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HBF2
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En12
  input   validIn;
  output  signed [15:0] dataOut;  // sfix16_En11
  output  validOut;


  wire syncReset;
  wire ctrl;
  wire ready;
  wire vldAndRdy;
  wire signed [16:0] dataIn_cast;  // sfix17_En12
  reg signed [16:0] delayLine;  // sfix17_En12
  wire signed [33:0] subfilterOutTmp_1;  // sfix34_En28
  wire vldAndRdy_1;
  reg signed [16:0] delayLine_1;  // sfix17_En12
  wire signed [33:0] subfilterOutTmp_2;  // sfix34_En28
  wire subfilterOutTmp_vld2;
  wire signed [15:0] accOut;  // sfix16_En11
  wire accOutVld;
  wire signed [15:0] ZERO_OUT;  // sfix16_En11
  wire signed [15:0] muxOut;  // sfix16_En11
  reg signed [15:0] dataOut_1;  // sfix16_En11
  reg  validOut_1;


  assign syncReset = 1'b0;

  partlySerialCtrl_block u_partlySerialCtrl (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .validIn(validIn),
                                             .ctrl(ctrl),
                                             .ready(ready)
                                             );

  assign vldAndRdy = validIn & ready;

  assign dataIn_cast = {dataIn[15], dataIn};

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        delayLine <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            delayLine <= 17'sb00000000000000000;
          end
          else begin
            if (vldAndRdy) begin
              delayLine <= dataIn_cast;
            end
          end
        end
      end
    end

  FIRPartlySerial_block1 u_FIRDecim_phase_1 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .filterInput(delayLine),  // sfix17_En12
                                             .ctrl(ctrl),
                                             .subfilterOutTmp_1(subfilterOutTmp_1)  // sfix34_En28
                                             );

  assign vldAndRdy_1 = validIn & ready;

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        delayLine_1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            delayLine_1 <= 17'sb00000000000000000;
          end
          else begin
            if (vldAndRdy_1) begin
              delayLine_1 <= delayLine;
            end
          end
        end
      end
    end

  FIRPartlySerial_block2 u_FIRDecim_phase_2 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .filterInput(delayLine_1),  // sfix17_En12
                                             .ctrl(ctrl),
                                             .subfilterOutTmp_2(subfilterOutTmp_2),  // sfix34_En28
                                             .subfilterOutTmp_vld2(subfilterOutTmp_vld2)
                                             );

  sumTree_firdecim_block u_FirDecimAccum_2 (.clk(clk),
                                            .reset(reset),
                                            .enb(enb),
                                            .accIn_0(subfilterOutTmp_1),  // sfix34_En28
                                            .accIn_1(subfilterOutTmp_2),  // sfix34_En28
                                            .subfilterOut_vld2(subfilterOutTmp_vld2),
                                            .accOut(accOut),  // sfix16_En11
                                            .accOutVld(accOutVld)
                                            );

  assign ZERO_OUT = 16'sb0000000000000000;

  assign muxOut = (accOutVld == 1'b0 ? ZERO_OUT :
              accOut);

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dataOut_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dataOut_1 <= 16'sb0000000000000000;
          end
          else begin
            dataOut_1 <= muxOut;
          end
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        validOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            validOut_1 <= 1'b0;
          end
          else begin
            validOut_1 <= accOutVld;
          end
        end
      end
    end

  assign dataOut = dataOut_1;

  assign validOut = validOut_1;

endmodule  // HBF2

