// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\iSection.v
// Created: 2026-01-30 11:58:04
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: iSection
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/CICDecimation/iSection
// Hierarchy Level: 2
// Model version: 17.90
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module iSection
          (clk,
           reset,
           enb,
           dataInreg,
           validInreg,
           internalReset,
           integOut_re,
           integOut_im);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataInreg;  // sfix16_En14
  input   validInreg;
  input   internalReset;
  output  signed [22:0] integOut_re;  // sfix23
  output  signed [22:0] integOut_im;  // sfix23


  wire signed [34:0] iIn_re1;  // sfix35_En12
  wire signed [34:0] iOut_re1;  // sfix35_En12
  wire signed [35:0] adder_add_cast;  // sfix36_En12
  wire signed [35:0] adder_add_cast_1;  // sfix36_En12
  wire signed [35:0] addOut_re1;  // sfix36_En12
  reg signed [35:0] iOutreg_re1;  // sfix36_En12
  wire signed [27:0] iIn_re2;  // sfix28_En5
  wire signed [27:0] iOut_re2;  // sfix28_En5
  wire signed [28:0] adder_add_cast_2;  // sfix29_En5
  wire signed [28:0] adder_add_cast_3;  // sfix29_En5
  wire signed [28:0] addOut_re2;  // sfix29_En5
  reg signed [28:0] iOutreg_re2;  // sfix29_En5
  wire signed [22:0] iIn_re3;  // sfix23
  wire signed [22:0] iOut_re3;  // sfix23
  wire signed [23:0] adder_3;  // sfix24
  wire signed [23:0] adder_4;  // sfix24
  wire signed [23:0] addOut_re3;  // sfix24
  reg signed [23:0] iOutreg_re3;  // sfix24
  wire signed [15:0] dtc_im;  // sfix16_En14
  wire signed [34:0] iIn_im1;  // sfix35_En12
  wire signed [34:0] iOut_im1;  // sfix35_En12
  wire signed [35:0] adder_add_cast_4;  // sfix36_En12
  wire signed [35:0] adder_add_cast_5;  // sfix36_En12
  wire signed [35:0] addOut_im1;  // sfix36_En12
  reg signed [35:0] iOutreg_im1;  // sfix36_En12
  wire signed [27:0] iIn_im2;  // sfix28_En5
  wire signed [27:0] iOut_im2;  // sfix28_En5
  wire signed [28:0] adder_add_cast_6;  // sfix29_En5
  wire signed [28:0] adder_add_cast_7;  // sfix29_En5
  wire signed [28:0] addOut_im2;  // sfix29_En5
  reg signed [28:0] iOutreg_im2;  // sfix29_En5
  wire signed [22:0] iIn_im3;  // sfix23
  wire signed [22:0] iOut_im3;  // sfix23
  wire signed [23:0] adder_8;  // sfix24
  wire signed [23:0] adder_9;  // sfix24
  wire signed [23:0] addOut_im3;  // sfix24
  reg signed [23:0] iOutreg_im3;  // sfix24


  assign iIn_re1 = {{21{dataInreg[15]}}, dataInreg[15:2]};

  assign adder_add_cast = {iIn_re1[34], iIn_re1};
  assign adder_add_cast_1 = {iOut_re1[34], iOut_re1};
  assign addOut_re1 = adder_add_cast + adder_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        iOutreg_re1 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_re1 <= 36'sh000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_re1 <= addOut_re1;
            end
          end
        end
      end
    end

  assign iOut_re1 = iOutreg_re1[34:0];

  assign iIn_re2 = iOut_re1[34:7];

  assign adder_add_cast_2 = {iIn_re2[27], iIn_re2};
  assign adder_add_cast_3 = {iOut_re2[27], iOut_re2};
  assign addOut_re2 = adder_add_cast_2 + adder_add_cast_3;

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        iOutreg_re2 <= 29'sb00000000000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_re2 <= 29'sb00000000000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_re2 <= addOut_re2;
            end
          end
        end
      end
    end

  assign iOut_re2 = iOutreg_re2[27:0];

  assign iIn_re3 = iOut_re2[27:5];

  assign adder_3 = {iIn_re3[22], iIn_re3};
  assign adder_4 = {iOut_re3[22], iOut_re3};
  assign addOut_re3 = adder_3 + adder_4;

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        iOutreg_re3 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_re3 <= 24'sb000000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_re3 <= addOut_re3;
            end
          end
        end
      end
    end

  assign iOut_re3 = iOutreg_re3[22:0];

  assign integOut_re = iOut_re3;

  assign dtc_im = 16'sb0000000000000000;

  assign iIn_im1 = {{21{dtc_im[15]}}, dtc_im[15:2]};

  assign adder_add_cast_4 = {iIn_im1[34], iIn_im1};
  assign adder_add_cast_5 = {iOut_im1[34], iOut_im1};
  assign addOut_im1 = adder_add_cast_4 + adder_add_cast_5;

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        iOutreg_im1 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_im1 <= 36'sh000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_im1 <= addOut_im1;
            end
          end
        end
      end
    end

  assign iOut_im1 = iOutreg_im1[34:0];

  assign iIn_im2 = iOut_im1[34:7];

  assign adder_add_cast_6 = {iIn_im2[27], iIn_im2};
  assign adder_add_cast_7 = {iOut_im2[27], iOut_im2};
  assign addOut_im2 = adder_add_cast_6 + adder_add_cast_7;

  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        iOutreg_im2 <= 29'sb00000000000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_im2 <= 29'sb00000000000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_im2 <= addOut_im2;
            end
          end
        end
      end
    end

  assign iOut_im2 = iOutreg_im2[27:0];

  assign iIn_im3 = iOut_im2[27:5];

  assign adder_8 = {iIn_im3[22], iIn_im3};
  assign adder_9 = {iOut_im3[22], iOut_im3};
  assign addOut_im3 = adder_8 + adder_9;

  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        iOutreg_im3 <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          if (internalReset == 1'b1) begin
            iOutreg_im3 <= 24'sb000000000000000000000000;
          end
          else begin
            if (validInreg) begin
              iOutreg_im3 <= addOut_im3;
            end
          end
        end
      end
    end

  assign iOut_im3 = iOutreg_im3[22:0];

  assign integOut_im = iOut_im3;

endmodule  // iSection

