// -------------------------------------------------------------
// 
// File Name: F:\MyGit_Folder\DRMTS_FunknerSchwarz\behav\Verilog\dsm_l2_sim_deci_cic_HDLgeneration\sumTree_firdecim_block.v
// Created: 2026-01-26 17:23:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: sumTree_firdecim_block
// Source Path: dsm_l2_sim_deci_cic_HDLgeneration/DECIMATOR/HBF2/sumTree_firdecim
// Hierarchy Level: 2
// Model version: 17.86
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module sumTree_firdecim_block
          (clk,
           reset,
           enb,
           accIn_0,
           accIn_1,
           subfilterOut_vld2,
           accOut,
           accOutVld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [133:0] accIn_0;  // sfix134_En128
  input   signed [133:0] accIn_1;  // sfix134_En128
  input   subfilterOut_vld2;
  output  signed [131:0] accOut;  // sfix132_En127
  output  accOutVld;


  wire signed [133:0] accS_1;  // sfix134_En128
  reg signed [133:0] accReg_1;  // sfix134_En128
  wire signed [131:0] dout_cast;  // sfix132_En127
  reg signed [131:0] accOut_1;  // sfix132_En127
  reg  [1:0] intdelay_reg;  // ufix1 [2]


  assign accS_1 = accIn_0 + accIn_1;

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        accReg_1 <= 134'sh0000000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          accReg_1 <= accS_1;
        end
      end
    end

  assign dout_cast = accReg_1[132:1];

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        accOut_1 <= 132'sh000000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          accOut_1 <= dout_cast;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        intdelay_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          intdelay_reg[0] <= subfilterOut_vld2;
          intdelay_reg[1] <= intdelay_reg[0];
        end
      end
    end

  assign accOutVld = intdelay_reg[1];

  assign accOut = accOut_1;

endmodule  // sumTree_firdecim_block

